/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  ProviderInvoicesControllerGetByIdQueryResponse,
  ProviderInvoicesControllerGetByIdPathParams,
  ProviderInvoicesControllerGetById404,
  ProviderInvoicesControllerGetById500
} from '../../types/providerInvoicesController/GetById.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { providerInvoicesControllerGetById } from '../../clients/providerInvoicesController/getById.ts';

export const providerInvoicesControllerGetByIdSuspenseQueryKey = (
  id: ProviderInvoicesControllerGetByIdPathParams['id']
) => [{ url: '/v1/provider-invoices/:id', params: { id: id } }] as const;

export type ProviderInvoicesControllerGetByIdSuspenseQueryKey = ReturnType<
  typeof providerInvoicesControllerGetByIdSuspenseQueryKey
>;

export function providerInvoicesControllerGetByIdSuspenseQueryOptions(
  id: ProviderInvoicesControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = providerInvoicesControllerGetByIdSuspenseQueryKey(id);
  return queryOptions<
    ProviderInvoicesControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      | ProviderInvoicesControllerGetById404
      | ProviderInvoicesControllerGetById500
    >,
    ProviderInvoicesControllerGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return providerInvoicesControllerGetById(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/provider-invoices/:id}
 */
export function useProviderInvoicesControllerGetByIdSuspense<
  TData = ProviderInvoicesControllerGetByIdQueryResponse,
  TQueryKey extends QueryKey = ProviderInvoicesControllerGetByIdSuspenseQueryKey
>(
  id: ProviderInvoicesControllerGetByIdPathParams['id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ProviderInvoicesControllerGetByIdQueryResponse,
        ResponseErrorConfig<
          | ProviderInvoicesControllerGetById404
          | ProviderInvoicesControllerGetById500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    providerInvoicesControllerGetByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...providerInvoicesControllerGetByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | ProviderInvoicesControllerGetById404
      | ProviderInvoicesControllerGetById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
