/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  ProcessingMonthsControllerGetByIdQueryResponse,
  ProcessingMonthsControllerGetByIdPathParams,
  ProcessingMonthsControllerGetById404,
  ProcessingMonthsControllerGetById500
} from '../../types/processingMonthsController/GetById.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { processingMonthsControllerGetById } from '../../clients/processingMonthsController/getById.ts';

export const processingMonthsControllerGetByIdSuspenseQueryKey = (
  id: ProcessingMonthsControllerGetByIdPathParams['id']
) => [{ url: '/v1/processing-months/:id', params: { id: id } }] as const;

export type ProcessingMonthsControllerGetByIdSuspenseQueryKey = ReturnType<
  typeof processingMonthsControllerGetByIdSuspenseQueryKey
>;

export function processingMonthsControllerGetByIdSuspenseQueryOptions(
  id: ProcessingMonthsControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = processingMonthsControllerGetByIdSuspenseQueryKey(id);
  return queryOptions<
    ProcessingMonthsControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      | ProcessingMonthsControllerGetById404
      | ProcessingMonthsControllerGetById500
    >,
    ProcessingMonthsControllerGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return processingMonthsControllerGetById(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/processing-months/:id}
 */
export function useProcessingMonthsControllerGetByIdSuspense<
  TData = ProcessingMonthsControllerGetByIdQueryResponse,
  TQueryKey extends QueryKey = ProcessingMonthsControllerGetByIdSuspenseQueryKey
>(
  id: ProcessingMonthsControllerGetByIdPathParams['id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ProcessingMonthsControllerGetByIdQueryResponse,
        ResponseErrorConfig<
          | ProcessingMonthsControllerGetById404
          | ProcessingMonthsControllerGetById500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    processingMonthsControllerGetByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...processingMonthsControllerGetByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | ProcessingMonthsControllerGetById404
      | ProcessingMonthsControllerGetById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
