/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from '../ApiResponse.ts';
import type { GetPhoneLineResponse } from '../GetPhoneLineResponse.ts';

export type PhoneLinesControllerGetByIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type PhoneLinesControllerGetById200 = GetPhoneLineResponse;

/**
 * @description Not Found
 */
export type PhoneLinesControllerGetById404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PhoneLinesControllerGetById500 = ApiResponse;

export type PhoneLinesControllerGetByIdQueryResponse =
  PhoneLinesControllerGetById200;

export type PhoneLinesControllerGetByIdQuery = {
  Response: PhoneLinesControllerGetById200;
  PathParams: PhoneLinesControllerGetByIdPathParams;
  Errors: PhoneLinesControllerGetById404 | PhoneLinesControllerGetById500;
};
