/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from '../ApiResponse.ts';
import type { ListCustomerResponse } from '../ListCustomerResponse.ts';

export type CustomersControllerGetByIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type CustomersControllerGetById200 = ListCustomerResponse;

/**
 * @description Not Found
 */
export type CustomersControllerGetById404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type CustomersControllerGetById500 = ApiResponse;

export type CustomersControllerGetByIdQueryResponse =
  CustomersControllerGetById200;

export type CustomersControllerGetByIdQuery = {
  Response: CustomersControllerGetById200;
  PathParams: CustomersControllerGetByIdPathParams;
  Errors: CustomersControllerGetById404 | CustomersControllerGetById500;
};
