/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  CustomersControllerGetByIdQueryResponse,
  CustomersControllerGetByIdPathParams,
  CustomersControllerGetById404,
  CustomersControllerGetById500
} from '../../types/customersController/GetById.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { customersControllerGetById } from '../../clients/customersController/getById.ts';

export const customersControllerGetByIdQueryKey = (
  id: CustomersControllerGetByIdPathParams['id']
) => [{ url: '/v1/customers/:id', params: { id: id } }] as const;

export type CustomersControllerGetByIdQueryKey = ReturnType<
  typeof customersControllerGetByIdQueryKey
>;

export function customersControllerGetByIdQueryOptions(
  id: CustomersControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = customersControllerGetByIdQueryKey(id);
  return queryOptions<
    CustomersControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      CustomersControllerGetById404 | CustomersControllerGetById500
    >,
    CustomersControllerGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return customersControllerGetById(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/customers/:id}
 */
export function useCustomersControllerGetById<
  TData = CustomersControllerGetByIdQueryResponse,
  TQueryData = CustomersControllerGetByIdQueryResponse,
  TQueryKey extends QueryKey = CustomersControllerGetByIdQueryKey
>(
  id: CustomersControllerGetByIdPathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        CustomersControllerGetByIdQueryResponse,
        ResponseErrorConfig<
          CustomersControllerGetById404 | CustomersControllerGetById500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? customersControllerGetByIdQueryKey(id);

  const query = useQuery(
    {
      ...customersControllerGetByIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      CustomersControllerGetById404 | CustomersControllerGetById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
