/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse,
  DeleteV1CustomersIdAttachmentsAttachmentidPathParams,
  DeleteV1CustomersIdAttachmentsAttachmentid400,
  DeleteV1CustomersIdAttachmentsAttachmentid404,
  DeleteV1CustomersIdAttachmentsAttachmentid500
} from '../types/DeleteV1CustomersIdAttachmentsAttachmentid.ts';

function getDeleteV1CustomersIdAttachmentsAttachmentidUrl(
  id: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['id'],
  attachmentId: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['attachmentId']
) {
  const res = {
    method: 'DELETE',
    url: `/v1/customers/${id}/attachments/${attachmentId}` as const
  };
  return res;
}

/**
 * {@link /v1/customers/:id/attachments/:attachmentId}
 */
export async function deleteV1CustomersIdAttachmentsAttachmentid(
  id: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['id'],
  attachmentId: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['attachmentId'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse,
    ResponseErrorConfig<
      | DeleteV1CustomersIdAttachmentsAttachmentid400
      | DeleteV1CustomersIdAttachmentsAttachmentid404
      | DeleteV1CustomersIdAttachmentsAttachmentid500
    >,
    unknown
  >({
    method: 'DELETE',
    url: getDeleteV1CustomersIdAttachmentsAttachmentidUrl(
      id,
      attachmentId
    ).url.toString(),
    ...requestConfig
  });
  return res.data;
}
