/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  DeleteV1CustomersIdMutationResponse,
  DeleteV1CustomersIdPathParams,
  DeleteV1CustomersId400,
  DeleteV1CustomersId404,
  DeleteV1CustomersId500
} from '../types/DeleteV1CustomersId.ts';

function getDeleteV1CustomersIdUrl(id: DeleteV1CustomersIdPathParams['id']) {
  const res = { method: 'DELETE', url: `/v1/customers/${id}` as const };
  return res;
}

/**
 * {@link /v1/customers/:id}
 */
export async function deleteV1CustomersId(
  id: DeleteV1CustomersIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1CustomersId400 | DeleteV1CustomersId404 | DeleteV1CustomersId500
    >,
    unknown
  >({
    method: 'DELETE',
    url: getDeleteV1CustomersIdUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
