/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest,
  DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse,
  DeleteV1PhoneLinesIdCustomerLinksActivePathParams,
  DeleteV1PhoneLinesIdCustomerLinksActive400,
  DeleteV1PhoneLinesIdCustomerLinksActive404,
  DeleteV1PhoneLinesIdCustomerLinksActive409,
  DeleteV1PhoneLinesIdCustomerLinksActive500
} from '../types/DeleteV1PhoneLinesIdCustomerLinksActive.ts';

function getDeleteV1PhoneLinesIdCustomerLinksActiveUrl(
  id: DeleteV1PhoneLinesIdCustomerLinksActivePathParams['id']
) {
  const res = {
    method: 'DELETE',
    url: `/v1/phone-lines/${id}/customer-links/active` as const
  };
  return res;
}

/**
 * {@link /v1/phone-lines/:id/customer-links/active}
 */
export async function deleteV1PhoneLinesIdCustomerLinksActive(
  id: DeleteV1PhoneLinesIdCustomerLinksActivePathParams['id'],
  data: DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest,
  config: Partial<
    RequestConfig<DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse,
    ResponseErrorConfig<
      | DeleteV1PhoneLinesIdCustomerLinksActive400
      | DeleteV1PhoneLinesIdCustomerLinksActive404
      | DeleteV1PhoneLinesIdCustomerLinksActive409
      | DeleteV1PhoneLinesIdCustomerLinksActive500
    >,
    DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest
  >({
    method: 'DELETE',
    url: getDeleteV1PhoneLinesIdCustomerLinksActiveUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
