/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  DeleteV1ProvidersIdMutationResponse,
  DeleteV1ProvidersIdPathParams,
  DeleteV1ProvidersId400,
  DeleteV1ProvidersId404,
  DeleteV1ProvidersId500
} from '../types/DeleteV1ProvidersId.ts';

function getDeleteV1ProvidersIdUrl(id: DeleteV1ProvidersIdPathParams['id']) {
  const res = { method: 'DELETE', url: `/v1/providers/${id}` as const };
  return res;
}

/**
 * {@link /v1/providers/:id}
 */
export async function deleteV1ProvidersId(
  id: DeleteV1ProvidersIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1ProvidersId400 | DeleteV1ProvidersId404 | DeleteV1ProvidersId500
    >,
    unknown
  >({
    method: 'DELETE',
    url: getDeleteV1ProvidersIdUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
