/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1ProviderInvoicesQueryResponse,
  GetV1ProviderInvoicesQueryParams,
  GetV1ProviderInvoices400,
  GetV1ProviderInvoices500
} from '../types/GetV1ProviderInvoices.ts';

function getGetV1ProviderInvoicesUrl() {
  const res = { method: 'GET', url: `/v1/provider-invoices` as const };
  return res;
}

/**
 * {@link /v1/provider-invoices}
 */
export async function getV1ProviderInvoices(
  params?: GetV1ProviderInvoicesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1ProviderInvoicesQueryResponse,
    ResponseErrorConfig<GetV1ProviderInvoices400 | GetV1ProviderInvoices500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1ProviderInvoicesUrl().url.toString(),
    params,
    ...requestConfig
  });
  return res.data;
}
