/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1ProcessingMonthsQueryResponse,
  GetV1ProcessingMonthsQueryParams,
  GetV1ProcessingMonths400,
  GetV1ProcessingMonths500
} from '../types/GetV1ProcessingMonths.ts';

function getGetV1ProcessingMonthsUrl() {
  const res = { method: 'GET', url: `/v1/processing-months` as const };
  return res;
}

/**
 * {@link /v1/processing-months}
 */
export async function getV1ProcessingMonths(
  params?: GetV1ProcessingMonthsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1ProcessingMonthsQueryResponse,
    ResponseErrorConfig<GetV1ProcessingMonths400 | GetV1ProcessingMonths500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1ProcessingMonthsUrl().url.toString(),
    params,
    ...requestConfig
  });
  return res.data;
}
