/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1CustomersIdAttachmentsQueryResponse,
  GetV1CustomersIdAttachmentsPathParams,
  GetV1CustomersIdAttachments404,
  GetV1CustomersIdAttachments500
} from '../types/GetV1CustomersIdAttachments.ts';

function getGetV1CustomersIdAttachmentsUrl(
  id: GetV1CustomersIdAttachmentsPathParams['id']
) {
  const res = {
    method: 'GET',
    url: `/v1/customers/${id}/attachments` as const
  };
  return res;
}

/**
 * {@link /v1/customers/:id/attachments}
 */
export async function getV1CustomersIdAttachments(
  id: GetV1CustomersIdAttachmentsPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1CustomersIdAttachmentsQueryResponse,
    ResponseErrorConfig<
      GetV1CustomersIdAttachments404 | GetV1CustomersIdAttachments500
    >,
    unknown
  >({
    method: 'GET',
    url: getGetV1CustomersIdAttachmentsUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
