/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1CustomersIdPhoneLinesQueryResponse,
  GetV1CustomersIdPhoneLinesPathParams,
  GetV1CustomersIdPhoneLinesQueryParams,
  GetV1CustomersIdPhoneLines500
} from '../types/GetV1CustomersIdPhoneLines.ts';

function getGetV1CustomersIdPhoneLinesUrl(
  id: GetV1CustomersIdPhoneLinesPathParams['id']
) {
  const res = {
    method: 'GET',
    url: `/v1/customers/${id}/phone-lines` as const
  };
  return res;
}

/**
 * {@link /v1/customers/:id/phone-lines}
 */
export async function getV1CustomersIdPhoneLines(
  id: GetV1CustomersIdPhoneLinesPathParams['id'],
  params?: GetV1CustomersIdPhoneLinesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1CustomersIdPhoneLinesQueryResponse,
    ResponseErrorConfig<GetV1CustomersIdPhoneLines500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1CustomersIdPhoneLinesUrl(id).url.toString(),
    params,
    ...requestConfig
  });
  return res.data;
}
