/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1CostCentersQueryResponse,
  GetV1CostCentersQueryParams,
  GetV1CostCenters400,
  GetV1CostCenters500
} from '../types/GetV1CostCenters.ts';

function getGetV1CostCentersUrl() {
  const res = { method: 'GET', url: `/v1/cost-centers` as const };
  return res;
}

/**
 * {@link /v1/cost-centers}
 */
export async function getV1CostCenters(
  params?: GetV1CostCentersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1CostCentersQueryResponse,
    ResponseErrorConfig<GetV1CostCenters400 | GetV1CostCenters500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1CostCentersUrl().url.toString(),
    params,
    ...requestConfig
  });
  return res.data;
}
