/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1PhoneLinesQueryResponse,
  GetV1PhoneLinesQueryParams,
  GetV1PhoneLines400,
  GetV1PhoneLines500
} from '../types/GetV1PhoneLines.ts';

function getGetV1PhoneLinesUrl() {
  const res = { method: 'GET', url: `/v1/phone-lines` as const };
  return res;
}

/**
 * {@link /v1/phone-lines}
 */
export async function getV1PhoneLines(
  params?: GetV1PhoneLinesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1PhoneLinesQueryResponse,
    ResponseErrorConfig<GetV1PhoneLines400 | GetV1PhoneLines500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1PhoneLinesUrl().url.toString(),
    params,
    ...requestConfig
  });
  return res.data;
}
