/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1StatsDashboardQueryResponse,
  GetV1StatsDashboard500
} from '../types/GetV1StatsDashboard.ts';

function getGetV1StatsDashboardUrl() {
  const res = { method: 'GET', url: `/v1/stats/dashboard` as const };
  return res;
}

/**
 * {@link /v1/stats/dashboard}
 */
export async function getV1StatsDashboard(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1StatsDashboardQueryResponse,
    ResponseErrorConfig<GetV1StatsDashboard500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1StatsDashboardUrl().url.toString(),
    ...requestConfig
  });
  return res.data;
}
