/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
} from '../types/GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness.ts';

function getGetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessUrl(
  id: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['id'],
  processingMonthId: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['processingMonthId']
) {
  const res = {
    method: 'GET',
    url: `/v1/customers/${id}/processing-months/${processingMonthId}/billing-readiness` as const
  };
  return res;
}

/**
 * {@link /v1/customers/:id/processing-months/:processingMonthId/billing-readiness}
 */
export async function getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness(
  id: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['id'],
  processingMonthId: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['processingMonthId'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
    ResponseErrorConfig<
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
    >,
    unknown
  >({
    method: 'GET',
    url: getGetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessUrl(
      id,
      processingMonthId
    ).url.toString(),
    ...requestConfig
  });
  return res.data;
}
