/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1BillingCyclesQueryResponse,
  GetV1BillingCyclesQueryParams,
  GetV1BillingCycles400,
  GetV1BillingCycles500
} from '../types/GetV1BillingCycles.ts';

function getGetV1BillingCyclesUrl() {
  const res = { method: 'GET', url: `/v1/billing-cycles` as const };
  return res;
}

/**
 * {@link /v1/billing-cycles}
 */
export async function getV1BillingCycles(
  params?: GetV1BillingCyclesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1BillingCyclesQueryResponse,
    ResponseErrorConfig<GetV1BillingCycles400 | GetV1BillingCycles500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1BillingCyclesUrl().url.toString(),
    params,
    ...requestConfig
  });
  return res.data;
}
