/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1PhoneLinesIdCustomerLinksQueryResponse,
  GetV1PhoneLinesIdCustomerLinksPathParams,
  GetV1PhoneLinesIdCustomerLinks500
} from '../types/GetV1PhoneLinesIdCustomerLinks.ts';

function getGetV1PhoneLinesIdCustomerLinksUrl(
  id: GetV1PhoneLinesIdCustomerLinksPathParams['id']
) {
  const res = {
    method: 'GET',
    url: `/v1/phone-lines/${id}/customer-links` as const
  };
  return res;
}

/**
 * {@link /v1/phone-lines/:id/customer-links}
 */
export async function getV1PhoneLinesIdCustomerLinks(
  id: GetV1PhoneLinesIdCustomerLinksPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1PhoneLinesIdCustomerLinksQueryResponse,
    ResponseErrorConfig<GetV1PhoneLinesIdCustomerLinks500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1PhoneLinesIdCustomerLinksUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
