/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1ProvidersQueryResponse,
  GetV1ProvidersQueryParams,
  GetV1Providers400,
  GetV1Providers500
} from '../types/GetV1Providers.ts';

function getGetV1ProvidersUrl() {
  const res = { method: 'GET', url: `/v1/providers` as const };
  return res;
}

/**
 * {@link /v1/providers}
 */
export async function getV1Providers(
  params?: GetV1ProvidersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1ProvidersQueryResponse,
    ResponseErrorConfig<GetV1Providers400 | GetV1Providers500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1ProvidersUrl().url.toString(),
    params,
    ...requestConfig
  });
  return res.data;
}
