/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1CustomersIdProviderLinksQueryResponse,
  GetV1CustomersIdProviderLinksPathParams,
  GetV1CustomersIdProviderLinks500
} from '../types/GetV1CustomersIdProviderLinks.ts';

function getGetV1CustomersIdProviderLinksUrl(
  id: GetV1CustomersIdProviderLinksPathParams['id']
) {
  const res = {
    method: 'GET',
    url: `/v1/customers/${id}/provider-links` as const
  };
  return res;
}

/**
 * {@link /v1/customers/:id/provider-links}
 */
export async function getV1CustomersIdProviderLinks(
  id: GetV1CustomersIdProviderLinksPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1CustomersIdProviderLinksQueryResponse,
    ResponseErrorConfig<GetV1CustomersIdProviderLinks500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1CustomersIdProviderLinksUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
