/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  GetV1CustomersQueryResponse,
  GetV1CustomersQueryParams,
  GetV1Customers500
} from '../types/GetV1Customers.ts';

function getGetV1CustomersUrl() {
  const res = { method: 'GET', url: `/v1/customers` as const };
  return res;
}

/**
 * {@link /v1/customers}
 */
export async function getV1Customers(
  params?: GetV1CustomersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1CustomersQueryResponse,
    ResponseErrorConfig<GetV1Customers500>,
    unknown
  >({
    method: 'GET',
    url: getGetV1CustomersUrl().url.toString(),
    params,
    ...requestConfig
  });
  return res.data;
}
