/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PatchV1ProvidersIdMutationRequest,
  PatchV1ProvidersIdMutationResponse,
  PatchV1ProvidersIdPathParams,
  PatchV1ProvidersId400,
  PatchV1ProvidersId404,
  PatchV1ProvidersId409,
  PatchV1ProvidersId500
} from '../types/PatchV1ProvidersId.ts';

function getPatchV1ProvidersIdUrl(id: PatchV1ProvidersIdPathParams['id']) {
  const res = { method: 'PATCH', url: `/v1/providers/${id}` as const };
  return res;
}

/**
 * {@link /v1/providers/:id}
 */
export async function patchV1ProvidersId(
  id: PatchV1ProvidersIdPathParams['id'],
  data: PatchV1ProvidersIdMutationRequest,
  config: Partial<RequestConfig<PatchV1ProvidersIdMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1ProvidersId400
      | PatchV1ProvidersId404
      | PatchV1ProvidersId409
      | PatchV1ProvidersId500
    >,
    PatchV1ProvidersIdMutationRequest
  >({
    method: 'PATCH',
    url: getPatchV1ProvidersIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
