/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PatchV1BillingCyclesIdMutationRequest,
  PatchV1BillingCyclesIdMutationResponse,
  PatchV1BillingCyclesIdPathParams,
  PatchV1BillingCyclesId400,
  PatchV1BillingCyclesId404,
  PatchV1BillingCyclesId409,
  PatchV1BillingCyclesId500
} from '../types/PatchV1BillingCyclesId.ts';

function getPatchV1BillingCyclesIdUrl(
  id: PatchV1BillingCyclesIdPathParams['id']
) {
  const res = { method: 'PATCH', url: `/v1/billing-cycles/${id}` as const };
  return res;
}

/**
 * {@link /v1/billing-cycles/:id}
 */
export async function patchV1BillingCyclesId(
  id: PatchV1BillingCyclesIdPathParams['id'],
  data: PatchV1BillingCyclesIdMutationRequest,
  config: Partial<RequestConfig<PatchV1BillingCyclesIdMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchV1BillingCyclesIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1BillingCyclesId400
      | PatchV1BillingCyclesId404
      | PatchV1BillingCyclesId409
      | PatchV1BillingCyclesId500
    >,
    PatchV1BillingCyclesIdMutationRequest
  >({
    method: 'PATCH',
    url: getPatchV1BillingCyclesIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
