/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PatchV1CustomersIdMutationRequest,
  PatchV1CustomersIdMutationResponse,
  PatchV1CustomersIdPathParams,
  PatchV1CustomersId400,
  PatchV1CustomersId404,
  PatchV1CustomersId409,
  PatchV1CustomersId500
} from '../types/PatchV1CustomersId.ts';

function getPatchV1CustomersIdUrl(id: PatchV1CustomersIdPathParams['id']) {
  const res = { method: 'PATCH', url: `/v1/customers/${id}` as const };
  return res;
}

/**
 * {@link /v1/customers/:id}
 */
export async function patchV1CustomersId(
  id: PatchV1CustomersIdPathParams['id'],
  data: PatchV1CustomersIdMutationRequest,
  config: Partial<RequestConfig<PatchV1CustomersIdMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1CustomersId400
      | PatchV1CustomersId404
      | PatchV1CustomersId409
      | PatchV1CustomersId500
    >,
    PatchV1CustomersIdMutationRequest
  >({
    method: 'PATCH',
    url: getPatchV1CustomersIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
