/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1ProvidersMutationRequest,
  PostV1ProvidersMutationResponse,
  PostV1Providers400,
  PostV1Providers409,
  PostV1Providers500
} from '../types/PostV1Providers.ts';

function getPostV1ProvidersUrl() {
  const res = { method: 'POST', url: `/v1/providers` as const };
  return res;
}

/**
 * {@link /v1/providers}
 */
export async function postV1Providers(
  data: PostV1ProvidersMutationRequest,
  config: Partial<RequestConfig<PostV1ProvidersMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1ProvidersMutationResponse,
    ResponseErrorConfig<
      PostV1Providers400 | PostV1Providers409 | PostV1Providers500
    >,
    PostV1ProvidersMutationRequest
  >({
    method: 'POST',
    url: getPostV1ProvidersUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
