/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1PreSignedUrlsUploadMutationRequest,
  PostV1PreSignedUrlsUploadMutationResponse,
  PostV1PreSignedUrlsUpload400,
  PostV1PreSignedUrlsUpload500
} from '../types/PostV1PreSignedUrlsUpload.ts';

function getPostV1PreSignedUrlsUploadUrl() {
  const res = { method: 'POST', url: `/v1/pre-signed-urls/upload` as const };
  return res;
}

/**
 * {@link /v1/pre-signed-urls/upload}
 */
export async function postV1PreSignedUrlsUpload(
  data: PostV1PreSignedUrlsUploadMutationRequest,
  config: Partial<RequestConfig<PostV1PreSignedUrlsUploadMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1PreSignedUrlsUploadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsUpload400 | PostV1PreSignedUrlsUpload500
    >,
    PostV1PreSignedUrlsUploadMutationRequest
  >({
    method: 'POST',
    url: getPostV1PreSignedUrlsUploadUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
