/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1PreSignedUrlsDownloadMutationRequest,
  PostV1PreSignedUrlsDownloadMutationResponse,
  PostV1PreSignedUrlsDownload400,
  PostV1PreSignedUrlsDownload500
} from '../types/PostV1PreSignedUrlsDownload.ts';

function getPostV1PreSignedUrlsDownloadUrl() {
  const res = { method: 'POST', url: `/v1/pre-signed-urls/download` as const };
  return res;
}

/**
 * {@link /v1/pre-signed-urls/download}
 */
export async function postV1PreSignedUrlsDownload(
  data: PostV1PreSignedUrlsDownloadMutationRequest,
  config: Partial<RequestConfig<PostV1PreSignedUrlsDownloadMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1PreSignedUrlsDownloadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsDownload400 | PostV1PreSignedUrlsDownload500
    >,
    PostV1PreSignedUrlsDownloadMutationRequest
  >({
    method: 'POST',
    url: getPostV1PreSignedUrlsDownloadUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
