/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1CustomersIdAttachmentsMutationRequest,
  PostV1CustomersIdAttachmentsMutationResponse,
  PostV1CustomersIdAttachmentsPathParams,
  PostV1CustomersIdAttachments400,
  PostV1CustomersIdAttachments404,
  PostV1CustomersIdAttachments500
} from '../types/PostV1CustomersIdAttachments.ts';

function getPostV1CustomersIdAttachmentsUrl(
  id: PostV1CustomersIdAttachmentsPathParams['id']
) {
  const res = {
    method: 'POST',
    url: `/v1/customers/${id}/attachments` as const
  };
  return res;
}

/**
 * {@link /v1/customers/:id/attachments}
 */
export async function postV1CustomersIdAttachments(
  id: PostV1CustomersIdAttachmentsPathParams['id'],
  data: PostV1CustomersIdAttachmentsMutationRequest,
  config: Partial<
    RequestConfig<PostV1CustomersIdAttachmentsMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1CustomersIdAttachmentsMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdAttachments400
      | PostV1CustomersIdAttachments404
      | PostV1CustomersIdAttachments500
    >,
    PostV1CustomersIdAttachmentsMutationRequest
  >({
    method: 'POST',
    url: getPostV1CustomersIdAttachmentsUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
