/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1ProcessingMonthsIdCloseContingencyMutationRequest,
  PostV1ProcessingMonthsIdCloseContingencyMutationResponse,
  PostV1ProcessingMonthsIdCloseContingencyPathParams,
  PostV1ProcessingMonthsIdCloseContingency400,
  PostV1ProcessingMonthsIdCloseContingency404,
  PostV1ProcessingMonthsIdCloseContingency409,
  PostV1ProcessingMonthsIdCloseContingency500
} from '../types/PostV1ProcessingMonthsIdCloseContingency.ts';

function getPostV1ProcessingMonthsIdCloseContingencyUrl(
  id: PostV1ProcessingMonthsIdCloseContingencyPathParams['id']
) {
  const res = {
    method: 'POST',
    url: `/v1/processing-months/${id}/close-contingency` as const
  };
  return res;
}

/**
 * {@link /v1/processing-months/:id/close-contingency}
 */
export async function postV1ProcessingMonthsIdCloseContingency(
  id: PostV1ProcessingMonthsIdCloseContingencyPathParams['id'],
  data: PostV1ProcessingMonthsIdCloseContingencyMutationRequest,
  config: Partial<
    RequestConfig<PostV1ProcessingMonthsIdCloseContingencyMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1ProcessingMonthsIdCloseContingencyMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdCloseContingency400
      | PostV1ProcessingMonthsIdCloseContingency404
      | PostV1ProcessingMonthsIdCloseContingency409
      | PostV1ProcessingMonthsIdCloseContingency500
    >,
    PostV1ProcessingMonthsIdCloseContingencyMutationRequest
  >({
    method: 'POST',
    url: getPostV1ProcessingMonthsIdCloseContingencyUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
