/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1CustomersMutationRequest,
  PostV1CustomersMutationResponse,
  PostV1Customers400,
  PostV1Customers409,
  PostV1Customers500
} from '../types/PostV1Customers.ts';

function getPostV1CustomersUrl() {
  const res = { method: 'POST', url: `/v1/customers` as const };
  return res;
}

/**
 * {@link /v1/customers}
 */
export async function postV1Customers(
  data: PostV1CustomersMutationRequest,
  config: Partial<RequestConfig<PostV1CustomersMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1CustomersMutationResponse,
    ResponseErrorConfig<
      PostV1Customers400 | PostV1Customers409 | PostV1Customers500
    >,
    PostV1CustomersMutationRequest
  >({
    method: 'POST',
    url: getPostV1CustomersUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
