/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500
} from '../types/PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease.ts';

function getPostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseUrl(
  id: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['id'],
  processingMonthId: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['processingMonthId']
) {
  const res = {
    method: 'POST',
    url: `/v1/customers/${id}/processing-months/${processingMonthId}/manual-release` as const
  };
  return res;
}

/**
 * {@link /v1/customers/:id/processing-months/:processingMonthId/manual-release}
 */
export async function postV1CustomersIdProcessingMonthsProcessingmonthidManualRelease(
  id: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['id'],
  processingMonthId: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['processingMonthId'],
  data: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest,
  config: Partial<
    RequestConfig<PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500
    >,
    PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest
  >({
    method: 'POST',
    url: getPostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseUrl(
      id,
      processingMonthId
    ).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
