/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1ProviderInvoicesMutationRequest,
  PostV1ProviderInvoicesMutationResponse,
  PostV1ProviderInvoices400,
  PostV1ProviderInvoices500
} from '../types/PostV1ProviderInvoices.ts';

function getPostV1ProviderInvoicesUrl() {
  const res = { method: 'POST', url: `/v1/provider-invoices` as const };
  return res;
}

/**
 * {@link /v1/provider-invoices}
 */
export async function postV1ProviderInvoices(
  data: PostV1ProviderInvoicesMutationRequest,
  config: Partial<RequestConfig<PostV1ProviderInvoicesMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1ProviderInvoicesMutationResponse,
    ResponseErrorConfig<PostV1ProviderInvoices400 | PostV1ProviderInvoices500>,
    PostV1ProviderInvoicesMutationRequest
  >({
    method: 'POST',
    url: getPostV1ProviderInvoicesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
