/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1ProcessingMonthsIdCloseMutationResponse,
  PostV1ProcessingMonthsIdClosePathParams,
  PostV1ProcessingMonthsIdClose400,
  PostV1ProcessingMonthsIdClose404,
  PostV1ProcessingMonthsIdClose409,
  PostV1ProcessingMonthsIdClose500
} from '../types/PostV1ProcessingMonthsIdClose.ts';

function getPostV1ProcessingMonthsIdCloseUrl(
  id: PostV1ProcessingMonthsIdClosePathParams['id']
) {
  const res = {
    method: 'POST',
    url: `/v1/processing-months/${id}/close` as const
  };
  return res;
}

/**
 * {@link /v1/processing-months/:id/close}
 */
export async function postV1ProcessingMonthsIdClose(
  id: PostV1ProcessingMonthsIdClosePathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostV1ProcessingMonthsIdCloseMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdClose400
      | PostV1ProcessingMonthsIdClose404
      | PostV1ProcessingMonthsIdClose409
      | PostV1ProcessingMonthsIdClose500
    >,
    unknown
  >({
    method: 'POST',
    url: getPostV1ProcessingMonthsIdCloseUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
