/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1PhoneLinesIdCustomerLinksTransferMutationRequest,
  PostV1PhoneLinesIdCustomerLinksTransferMutationResponse,
  PostV1PhoneLinesIdCustomerLinksTransferPathParams,
  PostV1PhoneLinesIdCustomerLinksTransfer400,
  PostV1PhoneLinesIdCustomerLinksTransfer404,
  PostV1PhoneLinesIdCustomerLinksTransfer409,
  PostV1PhoneLinesIdCustomerLinksTransfer500
} from '../types/PostV1PhoneLinesIdCustomerLinksTransfer.ts';

function getPostV1PhoneLinesIdCustomerLinksTransferUrl(
  id: PostV1PhoneLinesIdCustomerLinksTransferPathParams['id']
) {
  const res = {
    method: 'POST',
    url: `/v1/phone-lines/${id}/customer-links/transfer` as const
  };
  return res;
}

/**
 * {@link /v1/phone-lines/:id/customer-links/transfer}
 */
export async function postV1PhoneLinesIdCustomerLinksTransfer(
  id: PostV1PhoneLinesIdCustomerLinksTransferPathParams['id'],
  data: PostV1PhoneLinesIdCustomerLinksTransferMutationRequest,
  config: Partial<
    RequestConfig<PostV1PhoneLinesIdCustomerLinksTransferMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1PhoneLinesIdCustomerLinksTransferMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinksTransfer400
      | PostV1PhoneLinesIdCustomerLinksTransfer404
      | PostV1PhoneLinesIdCustomerLinksTransfer409
      | PostV1PhoneLinesIdCustomerLinksTransfer500
    >,
    PostV1PhoneLinesIdCustomerLinksTransferMutationRequest
  >({
    method: 'POST',
    url: getPostV1PhoneLinesIdCustomerLinksTransferUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
