/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1ProcessingMonthsMutationRequest,
  PostV1ProcessingMonthsMutationResponse,
  PostV1ProcessingMonths400,
  PostV1ProcessingMonths500
} from '../types/PostV1ProcessingMonths.ts';

function getPostV1ProcessingMonthsUrl() {
  const res = { method: 'POST', url: `/v1/processing-months` as const };
  return res;
}

/**
 * {@link /v1/processing-months}
 */
export async function postV1ProcessingMonths(
  data: PostV1ProcessingMonthsMutationRequest,
  config: Partial<RequestConfig<PostV1ProcessingMonthsMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1ProcessingMonthsMutationResponse,
    ResponseErrorConfig<PostV1ProcessingMonths400 | PostV1ProcessingMonths500>,
    PostV1ProcessingMonthsMutationRequest
  >({
    method: 'POST',
    url: getPostV1ProcessingMonthsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
