/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1PhoneLinesIdCustomerLinksMutationRequest,
  PostV1PhoneLinesIdCustomerLinksMutationResponse,
  PostV1PhoneLinesIdCustomerLinksPathParams,
  PostV1PhoneLinesIdCustomerLinks400,
  PostV1PhoneLinesIdCustomerLinks404,
  PostV1PhoneLinesIdCustomerLinks409,
  PostV1PhoneLinesIdCustomerLinks500
} from '../types/PostV1PhoneLinesIdCustomerLinks.ts';

function getPostV1PhoneLinesIdCustomerLinksUrl(
  id: PostV1PhoneLinesIdCustomerLinksPathParams['id']
) {
  const res = {
    method: 'POST',
    url: `/v1/phone-lines/${id}/customer-links` as const
  };
  return res;
}

/**
 * {@link /v1/phone-lines/:id/customer-links}
 */
export async function postV1PhoneLinesIdCustomerLinks(
  id: PostV1PhoneLinesIdCustomerLinksPathParams['id'],
  data: PostV1PhoneLinesIdCustomerLinksMutationRequest,
  config: Partial<
    RequestConfig<PostV1PhoneLinesIdCustomerLinksMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1PhoneLinesIdCustomerLinksMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinks400
      | PostV1PhoneLinesIdCustomerLinks404
      | PostV1PhoneLinesIdCustomerLinks409
      | PostV1PhoneLinesIdCustomerLinks500
    >,
    PostV1PhoneLinesIdCustomerLinksMutationRequest
  >({
    method: 'POST',
    url: getPostV1PhoneLinesIdCustomerLinksUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
