/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PostV1BillingCyclesMutationRequest,
  PostV1BillingCyclesMutationResponse,
  PostV1BillingCycles400,
  PostV1BillingCycles500
} from '../types/PostV1BillingCycles.ts';

function getPostV1BillingCyclesUrl() {
  const res = { method: 'POST', url: `/v1/billing-cycles` as const };
  return res;
}

/**
 * {@link /v1/billing-cycles}
 */
export async function postV1BillingCycles(
  data: PostV1BillingCyclesMutationRequest,
  config: Partial<RequestConfig<PostV1BillingCyclesMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1BillingCyclesMutationResponse,
    ResponseErrorConfig<PostV1BillingCycles400 | PostV1BillingCycles500>,
    PostV1BillingCyclesMutationRequest
  >({
    method: 'POST',
    url: getPostV1BillingCyclesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { 'Content-Type': 'application/*+json', ...requestConfig.headers }
  });
  return res.data;
}
