/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  ProviderInvoicesControllerGetByIdQueryResponse,
  ProviderInvoicesControllerGetByIdPathParams,
  ProviderInvoicesControllerGetById404,
  ProviderInvoicesControllerGetById500
} from '../../types/providerInvoicesController/GetById.ts';

function getProviderInvoicesControllerGetByIdUrl(
  id: ProviderInvoicesControllerGetByIdPathParams['id']
) {
  const res = { method: 'GET', url: `/v1/provider-invoices/${id}` as const };
  return res;
}

/**
 * {@link /v1/provider-invoices/:id}
 */
export async function providerInvoicesControllerGetById(
  id: ProviderInvoicesControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ProviderInvoicesControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      | ProviderInvoicesControllerGetById404
      | ProviderInvoicesControllerGetById500
    >,
    unknown
  >({
    method: 'GET',
    url: getProviderInvoicesControllerGetByIdUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
