/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  DeleteV1CustomersIdMutationResponse,
  DeleteV1CustomersIdPathParams,
  DeleteV1CustomersId400,
  DeleteV1CustomersId404,
  DeleteV1CustomersId500
} from '../types/DeleteV1CustomersId.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { deleteV1CustomersId } from '../clients/deleteV1CustomersId.ts';

export const deleteV1CustomersIdMutationKey = () =>
  [{ url: '/v1/customers/:id' }] as const;

export type DeleteV1CustomersIdMutationKey = ReturnType<
  typeof deleteV1CustomersIdMutationKey
>;

export function deleteV1CustomersIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = deleteV1CustomersIdMutationKey();
  return mutationOptions<
    DeleteV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1CustomersId400 | DeleteV1CustomersId404 | DeleteV1CustomersId500
    >,
    { id: DeleteV1CustomersIdPathParams['id'] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteV1CustomersId(id, config);
    }
  });
}

/**
 * {@link /v1/customers/:id}
 */
export function useDeleteV1CustomersId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1CustomersIdMutationResponse,
      ResponseErrorConfig<
        DeleteV1CustomersId400 | DeleteV1CustomersId404 | DeleteV1CustomersId500
      >,
      { id: DeleteV1CustomersIdPathParams['id'] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteV1CustomersIdMutationKey();

  const baseOptions = deleteV1CustomersIdMutationOptions(
    config
  ) as UseMutationOptions<
    DeleteV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1CustomersId400 | DeleteV1CustomersId404 | DeleteV1CustomersId500
    >,
    { id: DeleteV1CustomersIdPathParams['id'] },
    TContext
  >;

  return useMutation<
    DeleteV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1CustomersId400 | DeleteV1CustomersId404 | DeleteV1CustomersId500
    >,
    { id: DeleteV1CustomersIdPathParams['id'] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    DeleteV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1CustomersId400 | DeleteV1CustomersId404 | DeleteV1CustomersId500
    >,
    { id: DeleteV1CustomersIdPathParams['id'] },
    TContext
  >;
}
