/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest,
  DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse,
  DeleteV1PhoneLinesIdCustomerLinksActivePathParams,
  DeleteV1PhoneLinesIdCustomerLinksActive400,
  DeleteV1PhoneLinesIdCustomerLinksActive404,
  DeleteV1PhoneLinesIdCustomerLinksActive409,
  DeleteV1PhoneLinesIdCustomerLinksActive500
} from '../types/DeleteV1PhoneLinesIdCustomerLinksActive.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { deleteV1PhoneLinesIdCustomerLinksActive } from '../clients/deleteV1PhoneLinesIdCustomerLinksActive.ts';

export const deleteV1PhoneLinesIdCustomerLinksActiveMutationKey = () =>
  [{ url: '/v1/phone-lines/:id/customer-links/active' }] as const;

export type DeleteV1PhoneLinesIdCustomerLinksActiveMutationKey = ReturnType<
  typeof deleteV1PhoneLinesIdCustomerLinksActiveMutationKey
>;

export function deleteV1PhoneLinesIdCustomerLinksActiveMutationOptions<
  TContext = unknown
>(
  config: Partial<
    RequestConfig<DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey = deleteV1PhoneLinesIdCustomerLinksActiveMutationKey();
  return mutationOptions<
    DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse,
    ResponseErrorConfig<
      | DeleteV1PhoneLinesIdCustomerLinksActive400
      | DeleteV1PhoneLinesIdCustomerLinksActive404
      | DeleteV1PhoneLinesIdCustomerLinksActive409
      | DeleteV1PhoneLinesIdCustomerLinksActive500
    >,
    {
      id: DeleteV1PhoneLinesIdCustomerLinksActivePathParams['id'];
      data: DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return deleteV1PhoneLinesIdCustomerLinksActive(id, data, config);
    }
  });
}

/**
 * {@link /v1/phone-lines/:id/customer-links/active}
 */
export function useDeleteV1PhoneLinesIdCustomerLinksActive<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse,
      ResponseErrorConfig<
        | DeleteV1PhoneLinesIdCustomerLinksActive400
        | DeleteV1PhoneLinesIdCustomerLinksActive404
        | DeleteV1PhoneLinesIdCustomerLinksActive409
        | DeleteV1PhoneLinesIdCustomerLinksActive500
      >,
      {
        id: DeleteV1PhoneLinesIdCustomerLinksActivePathParams['id'];
        data: DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest>
    > & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteV1PhoneLinesIdCustomerLinksActiveMutationKey();

  const baseOptions = deleteV1PhoneLinesIdCustomerLinksActiveMutationOptions(
    config
  ) as UseMutationOptions<
    DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse,
    ResponseErrorConfig<
      | DeleteV1PhoneLinesIdCustomerLinksActive400
      | DeleteV1PhoneLinesIdCustomerLinksActive404
      | DeleteV1PhoneLinesIdCustomerLinksActive409
      | DeleteV1PhoneLinesIdCustomerLinksActive500
    >,
    {
      id: DeleteV1PhoneLinesIdCustomerLinksActivePathParams['id'];
      data: DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest;
    },
    TContext
  >;

  return useMutation<
    DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse,
    ResponseErrorConfig<
      | DeleteV1PhoneLinesIdCustomerLinksActive400
      | DeleteV1PhoneLinesIdCustomerLinksActive404
      | DeleteV1PhoneLinesIdCustomerLinksActive409
      | DeleteV1PhoneLinesIdCustomerLinksActive500
    >,
    {
      id: DeleteV1PhoneLinesIdCustomerLinksActivePathParams['id'];
      data: DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse,
    ResponseErrorConfig<
      | DeleteV1PhoneLinesIdCustomerLinksActive400
      | DeleteV1PhoneLinesIdCustomerLinksActive404
      | DeleteV1PhoneLinesIdCustomerLinksActive409
      | DeleteV1PhoneLinesIdCustomerLinksActive500
    >,
    {
      id: DeleteV1PhoneLinesIdCustomerLinksActivePathParams['id'];
      data: DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest;
    },
    TContext
  >;
}
