/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  DeleteV1ProvidersIdMutationResponse,
  DeleteV1ProvidersIdPathParams,
  DeleteV1ProvidersId400,
  DeleteV1ProvidersId404,
  DeleteV1ProvidersId500
} from '../types/DeleteV1ProvidersId.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { deleteV1ProvidersId } from '../clients/deleteV1ProvidersId.ts';

export const deleteV1ProvidersIdMutationKey = () =>
  [{ url: '/v1/providers/:id' }] as const;

export type DeleteV1ProvidersIdMutationKey = ReturnType<
  typeof deleteV1ProvidersIdMutationKey
>;

export function deleteV1ProvidersIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = deleteV1ProvidersIdMutationKey();
  return mutationOptions<
    DeleteV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1ProvidersId400 | DeleteV1ProvidersId404 | DeleteV1ProvidersId500
    >,
    { id: DeleteV1ProvidersIdPathParams['id'] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteV1ProvidersId(id, config);
    }
  });
}

/**
 * {@link /v1/providers/:id}
 */
export function useDeleteV1ProvidersId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1ProvidersIdMutationResponse,
      ResponseErrorConfig<
        DeleteV1ProvidersId400 | DeleteV1ProvidersId404 | DeleteV1ProvidersId500
      >,
      { id: DeleteV1ProvidersIdPathParams['id'] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteV1ProvidersIdMutationKey();

  const baseOptions = deleteV1ProvidersIdMutationOptions(
    config
  ) as UseMutationOptions<
    DeleteV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1ProvidersId400 | DeleteV1ProvidersId404 | DeleteV1ProvidersId500
    >,
    { id: DeleteV1ProvidersIdPathParams['id'] },
    TContext
  >;

  return useMutation<
    DeleteV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1ProvidersId400 | DeleteV1ProvidersId404 | DeleteV1ProvidersId500
    >,
    { id: DeleteV1ProvidersIdPathParams['id'] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    DeleteV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      DeleteV1ProvidersId400 | DeleteV1ProvidersId404 | DeleteV1ProvidersId500
    >,
    { id: DeleteV1ProvidersIdPathParams['id'] },
    TContext
  >;
}
