/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse,
  DeleteV1CustomersIdAttachmentsAttachmentidPathParams,
  DeleteV1CustomersIdAttachmentsAttachmentid400,
  DeleteV1CustomersIdAttachmentsAttachmentid404,
  DeleteV1CustomersIdAttachmentsAttachmentid500
} from '../types/DeleteV1CustomersIdAttachmentsAttachmentid.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { deleteV1CustomersIdAttachmentsAttachmentid } from '../clients/deleteV1CustomersIdAttachmentsAttachmentid.ts';

export const deleteV1CustomersIdAttachmentsAttachmentidMutationKey = () =>
  [{ url: '/v1/customers/:id/attachments/:attachmentId' }] as const;

export type DeleteV1CustomersIdAttachmentsAttachmentidMutationKey = ReturnType<
  typeof deleteV1CustomersIdAttachmentsAttachmentidMutationKey
>;

export function deleteV1CustomersIdAttachmentsAttachmentidMutationOptions<
  TContext = unknown
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteV1CustomersIdAttachmentsAttachmentidMutationKey();
  return mutationOptions<
    DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse,
    ResponseErrorConfig<
      | DeleteV1CustomersIdAttachmentsAttachmentid400
      | DeleteV1CustomersIdAttachmentsAttachmentid404
      | DeleteV1CustomersIdAttachmentsAttachmentid500
    >,
    {
      id: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['id'];
      attachmentId: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['attachmentId'];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, attachmentId }) => {
      return deleteV1CustomersIdAttachmentsAttachmentid(
        id,
        attachmentId,
        config
      );
    }
  });
}

/**
 * {@link /v1/customers/:id/attachments/:attachmentId}
 */
export function useDeleteV1CustomersIdAttachmentsAttachmentid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse,
      ResponseErrorConfig<
        | DeleteV1CustomersIdAttachmentsAttachmentid400
        | DeleteV1CustomersIdAttachmentsAttachmentid404
        | DeleteV1CustomersIdAttachmentsAttachmentid500
      >,
      {
        id: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['id'];
        attachmentId: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['attachmentId'];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteV1CustomersIdAttachmentsAttachmentidMutationKey();

  const baseOptions = deleteV1CustomersIdAttachmentsAttachmentidMutationOptions(
    config
  ) as UseMutationOptions<
    DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse,
    ResponseErrorConfig<
      | DeleteV1CustomersIdAttachmentsAttachmentid400
      | DeleteV1CustomersIdAttachmentsAttachmentid404
      | DeleteV1CustomersIdAttachmentsAttachmentid500
    >,
    {
      id: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['id'];
      attachmentId: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['attachmentId'];
    },
    TContext
  >;

  return useMutation<
    DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse,
    ResponseErrorConfig<
      | DeleteV1CustomersIdAttachmentsAttachmentid400
      | DeleteV1CustomersIdAttachmentsAttachmentid404
      | DeleteV1CustomersIdAttachmentsAttachmentid500
    >,
    {
      id: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['id'];
      attachmentId: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['attachmentId'];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse,
    ResponseErrorConfig<
      | DeleteV1CustomersIdAttachmentsAttachmentid400
      | DeleteV1CustomersIdAttachmentsAttachmentid404
      | DeleteV1CustomersIdAttachmentsAttachmentid500
    >,
    {
      id: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['id'];
      attachmentId: DeleteV1CustomersIdAttachmentsAttachmentidPathParams['attachmentId'];
    },
    TContext
  >;
}
