/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1PhoneLinesQueryResponse,
  GetV1PhoneLinesQueryParams,
  GetV1PhoneLines400,
  GetV1PhoneLines500
} from '../types/GetV1PhoneLines.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1PhoneLines } from '../clients/getV1PhoneLines.ts';

export const getV1PhoneLinesQueryKey = (params?: GetV1PhoneLinesQueryParams) =>
  [{ url: '/v1/phone-lines' }, ...(params ? [params] : [])] as const;

export type GetV1PhoneLinesQueryKey = ReturnType<
  typeof getV1PhoneLinesQueryKey
>;

export function getV1PhoneLinesQueryOptions(
  params?: GetV1PhoneLinesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1PhoneLinesQueryKey(params);
  return queryOptions<
    GetV1PhoneLinesQueryResponse,
    ResponseErrorConfig<GetV1PhoneLines400 | GetV1PhoneLines500>,
    GetV1PhoneLinesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1PhoneLines(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/phone-lines}
 */
export function useGetV1PhoneLines<
  TData = GetV1PhoneLinesQueryResponse,
  TQueryData = GetV1PhoneLinesQueryResponse,
  TQueryKey extends QueryKey = GetV1PhoneLinesQueryKey
>(
  params?: GetV1PhoneLinesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1PhoneLinesQueryResponse,
        ResponseErrorConfig<GetV1PhoneLines400 | GetV1PhoneLines500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getV1PhoneLinesQueryKey(params);

  const query = useQuery(
    {
      ...getV1PhoneLinesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1PhoneLines400 | GetV1PhoneLines500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
