/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1ProcessingMonthsQueryResponse,
  GetV1ProcessingMonthsQueryParams,
  GetV1ProcessingMonths400,
  GetV1ProcessingMonths500
} from '../types/GetV1ProcessingMonths.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1ProcessingMonths } from '../clients/getV1ProcessingMonths.ts';

export const getV1ProcessingMonthsQueryKey = (
  params?: GetV1ProcessingMonthsQueryParams
) => [{ url: '/v1/processing-months' }, ...(params ? [params] : [])] as const;

export type GetV1ProcessingMonthsQueryKey = ReturnType<
  typeof getV1ProcessingMonthsQueryKey
>;

export function getV1ProcessingMonthsQueryOptions(
  params?: GetV1ProcessingMonthsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1ProcessingMonthsQueryKey(params);
  return queryOptions<
    GetV1ProcessingMonthsQueryResponse,
    ResponseErrorConfig<GetV1ProcessingMonths400 | GetV1ProcessingMonths500>,
    GetV1ProcessingMonthsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1ProcessingMonths(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/processing-months}
 */
export function useGetV1ProcessingMonths<
  TData = GetV1ProcessingMonthsQueryResponse,
  TQueryData = GetV1ProcessingMonthsQueryResponse,
  TQueryKey extends QueryKey = GetV1ProcessingMonthsQueryKey
>(
  params?: GetV1ProcessingMonthsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1ProcessingMonthsQueryResponse,
        ResponseErrorConfig<
          GetV1ProcessingMonths400 | GetV1ProcessingMonths500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1ProcessingMonthsQueryKey(params);

  const query = useQuery(
    {
      ...getV1ProcessingMonthsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1ProcessingMonths400 | GetV1ProcessingMonths500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
