/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1CustomersIdAttachmentsQueryResponse,
  GetV1CustomersIdAttachmentsPathParams,
  GetV1CustomersIdAttachments404,
  GetV1CustomersIdAttachments500
} from '../types/GetV1CustomersIdAttachments.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1CustomersIdAttachments } from '../clients/getV1CustomersIdAttachments.ts';

export const getV1CustomersIdAttachmentsQueryKey = (
  id: GetV1CustomersIdAttachmentsPathParams['id']
) => [{ url: '/v1/customers/:id/attachments', params: { id: id } }] as const;

export type GetV1CustomersIdAttachmentsQueryKey = ReturnType<
  typeof getV1CustomersIdAttachmentsQueryKey
>;

export function getV1CustomersIdAttachmentsQueryOptions(
  id: GetV1CustomersIdAttachmentsPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1CustomersIdAttachmentsQueryKey(id);
  return queryOptions<
    GetV1CustomersIdAttachmentsQueryResponse,
    ResponseErrorConfig<
      GetV1CustomersIdAttachments404 | GetV1CustomersIdAttachments500
    >,
    GetV1CustomersIdAttachmentsQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1CustomersIdAttachments(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/customers/:id/attachments}
 */
export function useGetV1CustomersIdAttachments<
  TData = GetV1CustomersIdAttachmentsQueryResponse,
  TQueryData = GetV1CustomersIdAttachmentsQueryResponse,
  TQueryKey extends QueryKey = GetV1CustomersIdAttachmentsQueryKey
>(
  id: GetV1CustomersIdAttachmentsPathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1CustomersIdAttachmentsQueryResponse,
        ResponseErrorConfig<
          GetV1CustomersIdAttachments404 | GetV1CustomersIdAttachments500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1CustomersIdAttachmentsQueryKey(id);

  const query = useQuery(
    {
      ...getV1CustomersIdAttachmentsQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetV1CustomersIdAttachments404 | GetV1CustomersIdAttachments500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
