/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1ProvidersQueryResponse,
  GetV1ProvidersQueryParams,
  GetV1Providers400,
  GetV1Providers500
} from '../types/GetV1Providers.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { getV1Providers } from '../clients/getV1Providers.ts';

export const getV1ProvidersSuspenseQueryKey = (
  params?: GetV1ProvidersQueryParams
) => [{ url: '/v1/providers' }, ...(params ? [params] : [])] as const;

export type GetV1ProvidersSuspenseQueryKey = ReturnType<
  typeof getV1ProvidersSuspenseQueryKey
>;

export function getV1ProvidersSuspenseQueryOptions(
  params?: GetV1ProvidersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1ProvidersSuspenseQueryKey(params);
  return queryOptions<
    GetV1ProvidersQueryResponse,
    ResponseErrorConfig<GetV1Providers400 | GetV1Providers500>,
    GetV1ProvidersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1Providers(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/providers}
 */
export function useGetV1ProvidersSuspense<
  TData = GetV1ProvidersQueryResponse,
  TQueryKey extends QueryKey = GetV1ProvidersSuspenseQueryKey
>(
  params?: GetV1ProvidersQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1ProvidersQueryResponse,
        ResponseErrorConfig<GetV1Providers400 | GetV1Providers500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1ProvidersSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getV1ProvidersSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetV1Providers400 | GetV1Providers500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
