/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1CustomersQueryResponse,
  GetV1CustomersQueryParams,
  GetV1Customers500
} from '../types/GetV1Customers.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1Customers } from '../clients/getV1Customers.ts';

export const getV1CustomersQueryKey = (params?: GetV1CustomersQueryParams) =>
  [{ url: '/v1/customers' }, ...(params ? [params] : [])] as const;

export type GetV1CustomersQueryKey = ReturnType<typeof getV1CustomersQueryKey>;

export function getV1CustomersQueryOptions(
  params?: GetV1CustomersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1CustomersQueryKey(params);
  return queryOptions<
    GetV1CustomersQueryResponse,
    ResponseErrorConfig<GetV1Customers500>,
    GetV1CustomersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1Customers(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/customers}
 */
export function useGetV1Customers<
  TData = GetV1CustomersQueryResponse,
  TQueryData = GetV1CustomersQueryResponse,
  TQueryKey extends QueryKey = GetV1CustomersQueryKey
>(
  params?: GetV1CustomersQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1CustomersQueryResponse,
        ResponseErrorConfig<GetV1Customers500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getV1CustomersQueryKey(params);

  const query = useQuery(
    {
      ...getV1CustomersQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetV1Customers500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
