/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1PhoneLinesIdCustomerLinksQueryResponse,
  GetV1PhoneLinesIdCustomerLinksPathParams,
  GetV1PhoneLinesIdCustomerLinks500
} from '../types/GetV1PhoneLinesIdCustomerLinks.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1PhoneLinesIdCustomerLinks } from '../clients/getV1PhoneLinesIdCustomerLinks.ts';

export const getV1PhoneLinesIdCustomerLinksQueryKey = (
  id: GetV1PhoneLinesIdCustomerLinksPathParams['id']
) =>
  [{ url: '/v1/phone-lines/:id/customer-links', params: { id: id } }] as const;

export type GetV1PhoneLinesIdCustomerLinksQueryKey = ReturnType<
  typeof getV1PhoneLinesIdCustomerLinksQueryKey
>;

export function getV1PhoneLinesIdCustomerLinksQueryOptions(
  id: GetV1PhoneLinesIdCustomerLinksPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1PhoneLinesIdCustomerLinksQueryKey(id);
  return queryOptions<
    GetV1PhoneLinesIdCustomerLinksQueryResponse,
    ResponseErrorConfig<GetV1PhoneLinesIdCustomerLinks500>,
    GetV1PhoneLinesIdCustomerLinksQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1PhoneLinesIdCustomerLinks(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/phone-lines/:id/customer-links}
 */
export function useGetV1PhoneLinesIdCustomerLinks<
  TData = GetV1PhoneLinesIdCustomerLinksQueryResponse,
  TQueryData = GetV1PhoneLinesIdCustomerLinksQueryResponse,
  TQueryKey extends QueryKey = GetV1PhoneLinesIdCustomerLinksQueryKey
>(
  id: GetV1PhoneLinesIdCustomerLinksPathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1PhoneLinesIdCustomerLinksQueryResponse,
        ResponseErrorConfig<GetV1PhoneLinesIdCustomerLinks500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1PhoneLinesIdCustomerLinksQueryKey(id);

  const query = useQuery(
    {
      ...getV1PhoneLinesIdCustomerLinksQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1PhoneLinesIdCustomerLinks500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
