/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1CustomersIdPhoneLinesQueryResponse,
  GetV1CustomersIdPhoneLinesPathParams,
  GetV1CustomersIdPhoneLinesQueryParams,
  GetV1CustomersIdPhoneLines500
} from '../types/GetV1CustomersIdPhoneLines.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1CustomersIdPhoneLines } from '../clients/getV1CustomersIdPhoneLines.ts';

export const getV1CustomersIdPhoneLinesQueryKey = (
  id: GetV1CustomersIdPhoneLinesPathParams['id'],
  params?: GetV1CustomersIdPhoneLinesQueryParams
) =>
  [
    { url: '/v1/customers/:id/phone-lines', params: { id: id } },
    ...(params ? [params] : [])
  ] as const;

export type GetV1CustomersIdPhoneLinesQueryKey = ReturnType<
  typeof getV1CustomersIdPhoneLinesQueryKey
>;

export function getV1CustomersIdPhoneLinesQueryOptions(
  id: GetV1CustomersIdPhoneLinesPathParams['id'],
  params?: GetV1CustomersIdPhoneLinesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1CustomersIdPhoneLinesQueryKey(id, params);
  return queryOptions<
    GetV1CustomersIdPhoneLinesQueryResponse,
    ResponseErrorConfig<GetV1CustomersIdPhoneLines500>,
    GetV1CustomersIdPhoneLinesQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1CustomersIdPhoneLines(id, params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/customers/:id/phone-lines}
 */
export function useGetV1CustomersIdPhoneLines<
  TData = GetV1CustomersIdPhoneLinesQueryResponse,
  TQueryData = GetV1CustomersIdPhoneLinesQueryResponse,
  TQueryKey extends QueryKey = GetV1CustomersIdPhoneLinesQueryKey
>(
  id: GetV1CustomersIdPhoneLinesPathParams['id'],
  params?: GetV1CustomersIdPhoneLinesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1CustomersIdPhoneLinesQueryResponse,
        ResponseErrorConfig<GetV1CustomersIdPhoneLines500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1CustomersIdPhoneLinesQueryKey(id, params);

  const query = useQuery(
    {
      ...getV1CustomersIdPhoneLinesQueryOptions(id, params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1CustomersIdPhoneLines500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
