/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1StatsDashboardQueryResponse,
  GetV1StatsDashboard500
} from '../types/GetV1StatsDashboard.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { getV1StatsDashboard } from '../clients/getV1StatsDashboard.ts';

export const getV1StatsDashboardSuspenseQueryKey = () =>
  [{ url: '/v1/stats/dashboard' }] as const;

export type GetV1StatsDashboardSuspenseQueryKey = ReturnType<
  typeof getV1StatsDashboardSuspenseQueryKey
>;

export function getV1StatsDashboardSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1StatsDashboardSuspenseQueryKey();
  return queryOptions<
    GetV1StatsDashboardQueryResponse,
    ResponseErrorConfig<GetV1StatsDashboard500>,
    GetV1StatsDashboardQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1StatsDashboard({
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/stats/dashboard}
 */
export function useGetV1StatsDashboardSuspense<
  TData = GetV1StatsDashboardQueryResponse,
  TQueryKey extends QueryKey = GetV1StatsDashboardSuspenseQueryKey
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1StatsDashboardQueryResponse,
        ResponseErrorConfig<GetV1StatsDashboard500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1StatsDashboardSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getV1StatsDashboardSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetV1StatsDashboard500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
