/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1BillingCyclesQueryResponse,
  GetV1BillingCyclesQueryParams,
  GetV1BillingCycles400,
  GetV1BillingCycles500
} from '../types/GetV1BillingCycles.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1BillingCycles } from '../clients/getV1BillingCycles.ts';

export const getV1BillingCyclesQueryKey = (
  params?: GetV1BillingCyclesQueryParams
) => [{ url: '/v1/billing-cycles' }, ...(params ? [params] : [])] as const;

export type GetV1BillingCyclesQueryKey = ReturnType<
  typeof getV1BillingCyclesQueryKey
>;

export function getV1BillingCyclesQueryOptions(
  params?: GetV1BillingCyclesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1BillingCyclesQueryKey(params);
  return queryOptions<
    GetV1BillingCyclesQueryResponse,
    ResponseErrorConfig<GetV1BillingCycles400 | GetV1BillingCycles500>,
    GetV1BillingCyclesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1BillingCycles(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/billing-cycles}
 */
export function useGetV1BillingCycles<
  TData = GetV1BillingCyclesQueryResponse,
  TQueryData = GetV1BillingCyclesQueryResponse,
  TQueryKey extends QueryKey = GetV1BillingCyclesQueryKey
>(
  params?: GetV1BillingCyclesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1BillingCyclesQueryResponse,
        ResponseErrorConfig<GetV1BillingCycles400 | GetV1BillingCycles500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1BillingCyclesQueryKey(params);

  const query = useQuery(
    {
      ...getV1BillingCyclesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1BillingCycles400 | GetV1BillingCycles500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
