/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1CustomersIdProviderLinksQueryResponse,
  GetV1CustomersIdProviderLinksPathParams,
  GetV1CustomersIdProviderLinks500
} from '../types/GetV1CustomersIdProviderLinks.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1CustomersIdProviderLinks } from '../clients/getV1CustomersIdProviderLinks.ts';

export const getV1CustomersIdProviderLinksQueryKey = (
  id: GetV1CustomersIdProviderLinksPathParams['id']
) => [{ url: '/v1/customers/:id/provider-links', params: { id: id } }] as const;

export type GetV1CustomersIdProviderLinksQueryKey = ReturnType<
  typeof getV1CustomersIdProviderLinksQueryKey
>;

export function getV1CustomersIdProviderLinksQueryOptions(
  id: GetV1CustomersIdProviderLinksPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1CustomersIdProviderLinksQueryKey(id);
  return queryOptions<
    GetV1CustomersIdProviderLinksQueryResponse,
    ResponseErrorConfig<GetV1CustomersIdProviderLinks500>,
    GetV1CustomersIdProviderLinksQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1CustomersIdProviderLinks(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/customers/:id/provider-links}
 */
export function useGetV1CustomersIdProviderLinks<
  TData = GetV1CustomersIdProviderLinksQueryResponse,
  TQueryData = GetV1CustomersIdProviderLinksQueryResponse,
  TQueryKey extends QueryKey = GetV1CustomersIdProviderLinksQueryKey
>(
  id: GetV1CustomersIdProviderLinksPathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1CustomersIdProviderLinksQueryResponse,
        ResponseErrorConfig<GetV1CustomersIdProviderLinks500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1CustomersIdProviderLinksQueryKey(id);

  const query = useQuery(
    {
      ...getV1CustomersIdProviderLinksQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1CustomersIdProviderLinks500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
