/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1StatsDashboardQueryResponse,
  GetV1StatsDashboard500
} from '../types/GetV1StatsDashboard.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1StatsDashboard } from '../clients/getV1StatsDashboard.ts';

export const getV1StatsDashboardQueryKey = () =>
  [{ url: '/v1/stats/dashboard' }] as const;

export type GetV1StatsDashboardQueryKey = ReturnType<
  typeof getV1StatsDashboardQueryKey
>;

export function getV1StatsDashboardQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1StatsDashboardQueryKey();
  return queryOptions<
    GetV1StatsDashboardQueryResponse,
    ResponseErrorConfig<GetV1StatsDashboard500>,
    GetV1StatsDashboardQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1StatsDashboard({
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/stats/dashboard}
 */
export function useGetV1StatsDashboard<
  TData = GetV1StatsDashboardQueryResponse,
  TQueryData = GetV1StatsDashboardQueryResponse,
  TQueryKey extends QueryKey = GetV1StatsDashboardQueryKey
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1StatsDashboardQueryResponse,
        ResponseErrorConfig<GetV1StatsDashboard500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getV1StatsDashboardQueryKey();

  const query = useQuery(
    {
      ...getV1StatsDashboardQueryOptions(config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetV1StatsDashboard500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
