/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
} from '../types/GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness } from '../clients/getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness.ts';

export const getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspenseQueryKey =
  (
    id: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['id'],
    processingMonthId: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['processingMonthId']
  ) =>
    [
      {
        url: '/v1/customers/:id/processing-months/:processingMonthId/billing-readiness',
        params: { id: id, processingMonthId: processingMonthId }
      }
    ] as const;

export type GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspenseQueryKey =
  ReturnType<
    typeof getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspenseQueryKey
  >;

export function getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspenseQueryOptions(
  id: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['id'],
  processingMonthId: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['processingMonthId'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey =
    getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspenseQueryKey(
      id,
      processingMonthId
    );
  return queryOptions<
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
    ResponseErrorConfig<
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
    >,
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
    typeof queryKey
  >({
    enabled: !!(id && processingMonthId),
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness(
        id,
        processingMonthId,
        { ...config, signal: config.signal ?? signal }
      );
    }
  });
}

/**
 * {@link /v1/customers/:id/processing-months/:processingMonthId/billing-readiness}
 */
export function useGetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspense<
  TData =
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
  TQueryKey extends QueryKey =
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspenseQueryKey
>(
  id: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['id'],
  processingMonthId: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['processingMonthId'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
        ResponseErrorConfig<
          | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404
          | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspenseQueryKey(
      id,
      processingMonthId
    );

  const query = useSuspenseQuery(
    {
      ...getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessSuspenseQueryOptions(
        id,
        processingMonthId,
        config
      ),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
