/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1ProviderInvoicesQueryResponse,
  GetV1ProviderInvoicesQueryParams,
  GetV1ProviderInvoices400,
  GetV1ProviderInvoices500
} from '../types/GetV1ProviderInvoices.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1ProviderInvoices } from '../clients/getV1ProviderInvoices.ts';

export const getV1ProviderInvoicesQueryKey = (
  params?: GetV1ProviderInvoicesQueryParams
) => [{ url: '/v1/provider-invoices' }, ...(params ? [params] : [])] as const;

export type GetV1ProviderInvoicesQueryKey = ReturnType<
  typeof getV1ProviderInvoicesQueryKey
>;

export function getV1ProviderInvoicesQueryOptions(
  params?: GetV1ProviderInvoicesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1ProviderInvoicesQueryKey(params);
  return queryOptions<
    GetV1ProviderInvoicesQueryResponse,
    ResponseErrorConfig<GetV1ProviderInvoices400 | GetV1ProviderInvoices500>,
    GetV1ProviderInvoicesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1ProviderInvoices(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/provider-invoices}
 */
export function useGetV1ProviderInvoices<
  TData = GetV1ProviderInvoicesQueryResponse,
  TQueryData = GetV1ProviderInvoicesQueryResponse,
  TQueryKey extends QueryKey = GetV1ProviderInvoicesQueryKey
>(
  params?: GetV1ProviderInvoicesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1ProviderInvoicesQueryResponse,
        ResponseErrorConfig<
          GetV1ProviderInvoices400 | GetV1ProviderInvoices500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1ProviderInvoicesQueryKey(params);

  const query = useQuery(
    {
      ...getV1ProviderInvoicesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1ProviderInvoices400 | GetV1ProviderInvoices500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
