/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1CostCentersQueryResponse,
  GetV1CostCentersQueryParams,
  GetV1CostCenters400,
  GetV1CostCenters500
} from '../types/GetV1CostCenters.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1CostCenters } from '../clients/getV1CostCenters.ts';

export const getV1CostCentersQueryKey = (
  params?: GetV1CostCentersQueryParams
) => [{ url: '/v1/cost-centers' }, ...(params ? [params] : [])] as const;

export type GetV1CostCentersQueryKey = ReturnType<
  typeof getV1CostCentersQueryKey
>;

export function getV1CostCentersQueryOptions(
  params?: GetV1CostCentersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1CostCentersQueryKey(params);
  return queryOptions<
    GetV1CostCentersQueryResponse,
    ResponseErrorConfig<GetV1CostCenters400 | GetV1CostCenters500>,
    GetV1CostCentersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1CostCenters(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/cost-centers}
 */
export function useGetV1CostCenters<
  TData = GetV1CostCentersQueryResponse,
  TQueryData = GetV1CostCentersQueryResponse,
  TQueryKey extends QueryKey = GetV1CostCentersQueryKey
>(
  params?: GetV1CostCentersQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1CostCentersQueryResponse,
        ResponseErrorConfig<GetV1CostCenters400 | GetV1CostCenters500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1CostCentersQueryKey(params);

  const query = useQuery(
    {
      ...getV1CostCentersQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1CostCenters400 | GetV1CostCenters500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
