/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1PhoneLinesQueryResponse,
  GetV1PhoneLinesQueryParams,
  GetV1PhoneLines400,
  GetV1PhoneLines500
} from '../types/GetV1PhoneLines.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { getV1PhoneLines } from '../clients/getV1PhoneLines.ts';

export const getV1PhoneLinesSuspenseQueryKey = (
  params?: GetV1PhoneLinesQueryParams
) => [{ url: '/v1/phone-lines' }, ...(params ? [params] : [])] as const;

export type GetV1PhoneLinesSuspenseQueryKey = ReturnType<
  typeof getV1PhoneLinesSuspenseQueryKey
>;

export function getV1PhoneLinesSuspenseQueryOptions(
  params?: GetV1PhoneLinesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1PhoneLinesSuspenseQueryKey(params);
  return queryOptions<
    GetV1PhoneLinesQueryResponse,
    ResponseErrorConfig<GetV1PhoneLines400 | GetV1PhoneLines500>,
    GetV1PhoneLinesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1PhoneLines(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/phone-lines}
 */
export function useGetV1PhoneLinesSuspense<
  TData = GetV1PhoneLinesQueryResponse,
  TQueryKey extends QueryKey = GetV1PhoneLinesSuspenseQueryKey
>(
  params?: GetV1PhoneLinesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1PhoneLinesQueryResponse,
        ResponseErrorConfig<GetV1PhoneLines400 | GetV1PhoneLines500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getV1PhoneLinesSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getV1PhoneLinesSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetV1PhoneLines400 | GetV1PhoneLines500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
