/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404,
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
} from '../types/GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness } from '../clients/getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness.ts';

export const getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryKey =
  (
    id: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['id'],
    processingMonthId: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['processingMonthId']
  ) =>
    [
      {
        url: '/v1/customers/:id/processing-months/:processingMonthId/billing-readiness',
        params: { id: id, processingMonthId: processingMonthId }
      }
    ] as const;

export type GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryKey =
  ReturnType<
    typeof getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryKey
  >;

export function getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryOptions(
  id: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['id'],
  processingMonthId: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['processingMonthId'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey =
    getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryKey(
      id,
      processingMonthId
    );
  return queryOptions<
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
    ResponseErrorConfig<
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
    >,
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
    typeof queryKey
  >({
    enabled: !!(id && processingMonthId),
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness(
        id,
        processingMonthId,
        { ...config, signal: config.signal ?? signal }
      );
    }
  });
}

/**
 * {@link /v1/customers/:id/processing-months/:processingMonthId/billing-readiness}
 */
export function useGetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness<
  TData =
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
  TQueryData =
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
  TQueryKey extends QueryKey =
    GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryKey
>(
  id: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['id'],
  processingMonthId: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams['processingMonthId'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse,
        ResponseErrorConfig<
          | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404
          | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryKey(
      id,
      processingMonthId
    );

  const query = useQuery(
    {
      ...getV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryOptions(
        id,
        processingMonthId,
        config
      ),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
