/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  GetV1ProvidersQueryResponse,
  GetV1ProvidersQueryParams,
  GetV1Providers400,
  GetV1Providers500
} from '../types/GetV1Providers.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getV1Providers } from '../clients/getV1Providers.ts';

export const getV1ProvidersQueryKey = (params?: GetV1ProvidersQueryParams) =>
  [{ url: '/v1/providers' }, ...(params ? [params] : [])] as const;

export type GetV1ProvidersQueryKey = ReturnType<typeof getV1ProvidersQueryKey>;

export function getV1ProvidersQueryOptions(
  params?: GetV1ProvidersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getV1ProvidersQueryKey(params);
  return queryOptions<
    GetV1ProvidersQueryResponse,
    ResponseErrorConfig<GetV1Providers400 | GetV1Providers500>,
    GetV1ProvidersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getV1Providers(params, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/providers}
 */
export function useGetV1Providers<
  TData = GetV1ProvidersQueryResponse,
  TQueryData = GetV1ProvidersQueryResponse,
  TQueryKey extends QueryKey = GetV1ProvidersQueryKey
>(
  params?: GetV1ProvidersQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1ProvidersQueryResponse,
        ResponseErrorConfig<GetV1Providers400 | GetV1Providers500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getV1ProvidersQueryKey(params);

  const query = useQuery(
    {
      ...getV1ProvidersQueryOptions(params, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetV1Providers400 | GetV1Providers500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
