/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409,
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500
} from '../types/PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1CustomersIdProcessingMonthsProcessingmonthidManualRelease } from '../clients/postV1CustomersIdProcessingMonthsProcessingmonthidManualRelease.ts';

export const postV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationKey =
  () =>
    [
      {
        url: '/v1/customers/:id/processing-months/:processingMonthId/manual-release'
      }
    ] as const;

export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationKey =
  ReturnType<
    typeof postV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationKey
  >;

export function postV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationOptions<
  TContext = unknown
>(
  config: Partial<
    RequestConfig<PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey =
    postV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationKey();
  return mutationOptions<
    PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500
    >,
    {
      id: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['id'];
      processingMonthId: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['processingMonthId'];
      data: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, processingMonthId, data }) => {
      return postV1CustomersIdProcessingMonthsProcessingmonthidManualRelease(
        id,
        processingMonthId,
        data,
        config
      );
    }
  });
}

/**
 * {@link /v1/customers/:id/processing-months/:processingMonthId/manual-release}
 */
export function usePostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease<
  TContext
>(
  options: {
    mutation?: UseMutationOptions<
      PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse,
      ResponseErrorConfig<
        | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400
        | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404
        | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409
        | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500
      >,
      {
        id: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['id'];
        processingMonthId: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['processingMonthId'];
        data: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest>
    > & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationKey();

  const baseOptions =
    postV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationOptions(
      config
    ) as UseMutationOptions<
      PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse,
      ResponseErrorConfig<
        | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400
        | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404
        | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409
        | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500
      >,
      {
        id: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['id'];
        processingMonthId: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['processingMonthId'];
        data: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest;
      },
      TContext
    >;

  return useMutation<
    PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500
    >,
    {
      id: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['id'];
      processingMonthId: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['processingMonthId'];
      data: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500
    >,
    {
      id: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['id'];
      processingMonthId: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams['processingMonthId'];
      data: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest;
    },
    TContext
  >;
}
