/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1BillingCyclesMutationRequest,
  PostV1BillingCyclesMutationResponse,
  PostV1BillingCycles400,
  PostV1BillingCycles500
} from '../types/PostV1BillingCycles.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1BillingCycles } from '../clients/postV1BillingCycles.ts';

export const postV1BillingCyclesMutationKey = () =>
  [{ url: '/v1/billing-cycles' }] as const;

export type PostV1BillingCyclesMutationKey = ReturnType<
  typeof postV1BillingCyclesMutationKey
>;

export function postV1BillingCyclesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1BillingCyclesMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = postV1BillingCyclesMutationKey();
  return mutationOptions<
    PostV1BillingCyclesMutationResponse,
    ResponseErrorConfig<PostV1BillingCycles400 | PostV1BillingCycles500>,
    { data: PostV1BillingCyclesMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1BillingCycles(data, config);
    }
  });
}

/**
 * {@link /v1/billing-cycles}
 */
export function usePostV1BillingCycles<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1BillingCyclesMutationResponse,
      ResponseErrorConfig<PostV1BillingCycles400 | PostV1BillingCycles500>,
      { data: PostV1BillingCyclesMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostV1BillingCyclesMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1BillingCyclesMutationKey();

  const baseOptions = postV1BillingCyclesMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1BillingCyclesMutationResponse,
    ResponseErrorConfig<PostV1BillingCycles400 | PostV1BillingCycles500>,
    { data: PostV1BillingCyclesMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1BillingCyclesMutationResponse,
    ResponseErrorConfig<PostV1BillingCycles400 | PostV1BillingCycles500>,
    { data: PostV1BillingCyclesMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1BillingCyclesMutationResponse,
    ResponseErrorConfig<PostV1BillingCycles400 | PostV1BillingCycles500>,
    { data: PostV1BillingCyclesMutationRequest },
    TContext
  >;
}
