/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1ProcessingMonthsIdCloseContingencyMutationRequest,
  PostV1ProcessingMonthsIdCloseContingencyMutationResponse,
  PostV1ProcessingMonthsIdCloseContingencyPathParams,
  PostV1ProcessingMonthsIdCloseContingency400,
  PostV1ProcessingMonthsIdCloseContingency404,
  PostV1ProcessingMonthsIdCloseContingency409,
  PostV1ProcessingMonthsIdCloseContingency500
} from '../types/PostV1ProcessingMonthsIdCloseContingency.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1ProcessingMonthsIdCloseContingency } from '../clients/postV1ProcessingMonthsIdCloseContingency.ts';

export const postV1ProcessingMonthsIdCloseContingencyMutationKey = () =>
  [{ url: '/v1/processing-months/:id/close-contingency' }] as const;

export type PostV1ProcessingMonthsIdCloseContingencyMutationKey = ReturnType<
  typeof postV1ProcessingMonthsIdCloseContingencyMutationKey
>;

export function postV1ProcessingMonthsIdCloseContingencyMutationOptions<
  TContext = unknown
>(
  config: Partial<
    RequestConfig<PostV1ProcessingMonthsIdCloseContingencyMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey = postV1ProcessingMonthsIdCloseContingencyMutationKey();
  return mutationOptions<
    PostV1ProcessingMonthsIdCloseContingencyMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdCloseContingency400
      | PostV1ProcessingMonthsIdCloseContingency404
      | PostV1ProcessingMonthsIdCloseContingency409
      | PostV1ProcessingMonthsIdCloseContingency500
    >,
    {
      id: PostV1ProcessingMonthsIdCloseContingencyPathParams['id'];
      data: PostV1ProcessingMonthsIdCloseContingencyMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postV1ProcessingMonthsIdCloseContingency(id, data, config);
    }
  });
}

/**
 * {@link /v1/processing-months/:id/close-contingency}
 */
export function usePostV1ProcessingMonthsIdCloseContingency<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1ProcessingMonthsIdCloseContingencyMutationResponse,
      ResponseErrorConfig<
        | PostV1ProcessingMonthsIdCloseContingency400
        | PostV1ProcessingMonthsIdCloseContingency404
        | PostV1ProcessingMonthsIdCloseContingency409
        | PostV1ProcessingMonthsIdCloseContingency500
      >,
      {
        id: PostV1ProcessingMonthsIdCloseContingencyPathParams['id'];
        data: PostV1ProcessingMonthsIdCloseContingencyMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1ProcessingMonthsIdCloseContingencyMutationRequest>
    > & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postV1ProcessingMonthsIdCloseContingencyMutationKey();

  const baseOptions = postV1ProcessingMonthsIdCloseContingencyMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1ProcessingMonthsIdCloseContingencyMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdCloseContingency400
      | PostV1ProcessingMonthsIdCloseContingency404
      | PostV1ProcessingMonthsIdCloseContingency409
      | PostV1ProcessingMonthsIdCloseContingency500
    >,
    {
      id: PostV1ProcessingMonthsIdCloseContingencyPathParams['id'];
      data: PostV1ProcessingMonthsIdCloseContingencyMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostV1ProcessingMonthsIdCloseContingencyMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdCloseContingency400
      | PostV1ProcessingMonthsIdCloseContingency404
      | PostV1ProcessingMonthsIdCloseContingency409
      | PostV1ProcessingMonthsIdCloseContingency500
    >,
    {
      id: PostV1ProcessingMonthsIdCloseContingencyPathParams['id'];
      data: PostV1ProcessingMonthsIdCloseContingencyMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1ProcessingMonthsIdCloseContingencyMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdCloseContingency400
      | PostV1ProcessingMonthsIdCloseContingency404
      | PostV1ProcessingMonthsIdCloseContingency409
      | PostV1ProcessingMonthsIdCloseContingency500
    >,
    {
      id: PostV1ProcessingMonthsIdCloseContingencyPathParams['id'];
      data: PostV1ProcessingMonthsIdCloseContingencyMutationRequest;
    },
    TContext
  >;
}
