/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PatchV1CustomersIdMutationRequest,
  PatchV1CustomersIdMutationResponse,
  PatchV1CustomersIdPathParams,
  PatchV1CustomersId400,
  PatchV1CustomersId404,
  PatchV1CustomersId409,
  PatchV1CustomersId500
} from '../types/PatchV1CustomersId.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { patchV1CustomersId } from '../clients/patchV1CustomersId.ts';

export const patchV1CustomersIdMutationKey = () =>
  [{ url: '/v1/customers/:id' }] as const;

export type PatchV1CustomersIdMutationKey = ReturnType<
  typeof patchV1CustomersIdMutationKey
>;

export function patchV1CustomersIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchV1CustomersIdMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = patchV1CustomersIdMutationKey();
  return mutationOptions<
    PatchV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1CustomersId400
      | PatchV1CustomersId404
      | PatchV1CustomersId409
      | PatchV1CustomersId500
    >,
    {
      id: PatchV1CustomersIdPathParams['id'];
      data: PatchV1CustomersIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchV1CustomersId(id, data, config);
    }
  });
}

/**
 * {@link /v1/customers/:id}
 */
export function usePatchV1CustomersId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchV1CustomersIdMutationResponse,
      ResponseErrorConfig<
        | PatchV1CustomersId400
        | PatchV1CustomersId404
        | PatchV1CustomersId409
        | PatchV1CustomersId500
      >,
      {
        id: PatchV1CustomersIdPathParams['id'];
        data: PatchV1CustomersIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchV1CustomersIdMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchV1CustomersIdMutationKey();

  const baseOptions = patchV1CustomersIdMutationOptions(
    config
  ) as UseMutationOptions<
    PatchV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1CustomersId400
      | PatchV1CustomersId404
      | PatchV1CustomersId409
      | PatchV1CustomersId500
    >,
    {
      id: PatchV1CustomersIdPathParams['id'];
      data: PatchV1CustomersIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1CustomersId400
      | PatchV1CustomersId404
      | PatchV1CustomersId409
      | PatchV1CustomersId500
    >,
    {
      id: PatchV1CustomersIdPathParams['id'];
      data: PatchV1CustomersIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PatchV1CustomersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1CustomersId400
      | PatchV1CustomersId404
      | PatchV1CustomersId409
      | PatchV1CustomersId500
    >,
    {
      id: PatchV1CustomersIdPathParams['id'];
      data: PatchV1CustomersIdMutationRequest;
    },
    TContext
  >;
}
