/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PatchV1BillingCyclesIdMutationRequest,
  PatchV1BillingCyclesIdMutationResponse,
  PatchV1BillingCyclesIdPathParams,
  PatchV1BillingCyclesId400,
  PatchV1BillingCyclesId404,
  PatchV1BillingCyclesId409,
  PatchV1BillingCyclesId500
} from '../types/PatchV1BillingCyclesId.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { patchV1BillingCyclesId } from '../clients/patchV1BillingCyclesId.ts';

export const patchV1BillingCyclesIdMutationKey = () =>
  [{ url: '/v1/billing-cycles/:id' }] as const;

export type PatchV1BillingCyclesIdMutationKey = ReturnType<
  typeof patchV1BillingCyclesIdMutationKey
>;

export function patchV1BillingCyclesIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchV1BillingCyclesIdMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = patchV1BillingCyclesIdMutationKey();
  return mutationOptions<
    PatchV1BillingCyclesIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1BillingCyclesId400
      | PatchV1BillingCyclesId404
      | PatchV1BillingCyclesId409
      | PatchV1BillingCyclesId500
    >,
    {
      id: PatchV1BillingCyclesIdPathParams['id'];
      data: PatchV1BillingCyclesIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchV1BillingCyclesId(id, data, config);
    }
  });
}

/**
 * {@link /v1/billing-cycles/:id}
 */
export function usePatchV1BillingCyclesId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchV1BillingCyclesIdMutationResponse,
      ResponseErrorConfig<
        | PatchV1BillingCyclesId400
        | PatchV1BillingCyclesId404
        | PatchV1BillingCyclesId409
        | PatchV1BillingCyclesId500
      >,
      {
        id: PatchV1BillingCyclesIdPathParams['id'];
        data: PatchV1BillingCyclesIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchV1BillingCyclesIdMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchV1BillingCyclesIdMutationKey();

  const baseOptions = patchV1BillingCyclesIdMutationOptions(
    config
  ) as UseMutationOptions<
    PatchV1BillingCyclesIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1BillingCyclesId400
      | PatchV1BillingCyclesId404
      | PatchV1BillingCyclesId409
      | PatchV1BillingCyclesId500
    >,
    {
      id: PatchV1BillingCyclesIdPathParams['id'];
      data: PatchV1BillingCyclesIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchV1BillingCyclesIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1BillingCyclesId400
      | PatchV1BillingCyclesId404
      | PatchV1BillingCyclesId409
      | PatchV1BillingCyclesId500
    >,
    {
      id: PatchV1BillingCyclesIdPathParams['id'];
      data: PatchV1BillingCyclesIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PatchV1BillingCyclesIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1BillingCyclesId400
      | PatchV1BillingCyclesId404
      | PatchV1BillingCyclesId409
      | PatchV1BillingCyclesId500
    >,
    {
      id: PatchV1BillingCyclesIdPathParams['id'];
      data: PatchV1BillingCyclesIdMutationRequest;
    },
    TContext
  >;
}
