/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1ProcessingMonthsIdCloseMutationResponse,
  PostV1ProcessingMonthsIdClosePathParams,
  PostV1ProcessingMonthsIdClose400,
  PostV1ProcessingMonthsIdClose404,
  PostV1ProcessingMonthsIdClose409,
  PostV1ProcessingMonthsIdClose500
} from '../types/PostV1ProcessingMonthsIdClose.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1ProcessingMonthsIdClose } from '../clients/postV1ProcessingMonthsIdClose.ts';

export const postV1ProcessingMonthsIdCloseMutationKey = () =>
  [{ url: '/v1/processing-months/:id/close' }] as const;

export type PostV1ProcessingMonthsIdCloseMutationKey = ReturnType<
  typeof postV1ProcessingMonthsIdCloseMutationKey
>;

export function postV1ProcessingMonthsIdCloseMutationOptions<
  TContext = unknown
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = postV1ProcessingMonthsIdCloseMutationKey();
  return mutationOptions<
    PostV1ProcessingMonthsIdCloseMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdClose400
      | PostV1ProcessingMonthsIdClose404
      | PostV1ProcessingMonthsIdClose409
      | PostV1ProcessingMonthsIdClose500
    >,
    { id: PostV1ProcessingMonthsIdClosePathParams['id'] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postV1ProcessingMonthsIdClose(id, config);
    }
  });
}

/**
 * {@link /v1/processing-months/:id/close}
 */
export function usePostV1ProcessingMonthsIdClose<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1ProcessingMonthsIdCloseMutationResponse,
      ResponseErrorConfig<
        | PostV1ProcessingMonthsIdClose400
        | PostV1ProcessingMonthsIdClose404
        | PostV1ProcessingMonthsIdClose409
        | PostV1ProcessingMonthsIdClose500
      >,
      { id: PostV1ProcessingMonthsIdClosePathParams['id'] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1ProcessingMonthsIdCloseMutationKey();

  const baseOptions = postV1ProcessingMonthsIdCloseMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1ProcessingMonthsIdCloseMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdClose400
      | PostV1ProcessingMonthsIdClose404
      | PostV1ProcessingMonthsIdClose409
      | PostV1ProcessingMonthsIdClose500
    >,
    { id: PostV1ProcessingMonthsIdClosePathParams['id'] },
    TContext
  >;

  return useMutation<
    PostV1ProcessingMonthsIdCloseMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdClose400
      | PostV1ProcessingMonthsIdClose404
      | PostV1ProcessingMonthsIdClose409
      | PostV1ProcessingMonthsIdClose500
    >,
    { id: PostV1ProcessingMonthsIdClosePathParams['id'] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1ProcessingMonthsIdCloseMutationResponse,
    ResponseErrorConfig<
      | PostV1ProcessingMonthsIdClose400
      | PostV1ProcessingMonthsIdClose404
      | PostV1ProcessingMonthsIdClose409
      | PostV1ProcessingMonthsIdClose500
    >,
    { id: PostV1ProcessingMonthsIdClosePathParams['id'] },
    TContext
  >;
}
