/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1CustomersMutationRequest,
  PostV1CustomersMutationResponse,
  PostV1Customers400,
  PostV1Customers409,
  PostV1Customers500
} from '../types/PostV1Customers.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1Customers } from '../clients/postV1Customers.ts';

export const postV1CustomersMutationKey = () =>
  [{ url: '/v1/customers' }] as const;

export type PostV1CustomersMutationKey = ReturnType<
  typeof postV1CustomersMutationKey
>;

export function postV1CustomersMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1CustomersMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = postV1CustomersMutationKey();
  return mutationOptions<
    PostV1CustomersMutationResponse,
    ResponseErrorConfig<
      PostV1Customers400 | PostV1Customers409 | PostV1Customers500
    >,
    { data: PostV1CustomersMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1Customers(data, config);
    }
  });
}

/**
 * {@link /v1/customers}
 */
export function usePostV1Customers<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1CustomersMutationResponse,
      ResponseErrorConfig<
        PostV1Customers400 | PostV1Customers409 | PostV1Customers500
      >,
      { data: PostV1CustomersMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostV1CustomersMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1CustomersMutationKey();

  const baseOptions = postV1CustomersMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1CustomersMutationResponse,
    ResponseErrorConfig<
      PostV1Customers400 | PostV1Customers409 | PostV1Customers500
    >,
    { data: PostV1CustomersMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1CustomersMutationResponse,
    ResponseErrorConfig<
      PostV1Customers400 | PostV1Customers409 | PostV1Customers500
    >,
    { data: PostV1CustomersMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1CustomersMutationResponse,
    ResponseErrorConfig<
      PostV1Customers400 | PostV1Customers409 | PostV1Customers500
    >,
    { data: PostV1CustomersMutationRequest },
    TContext
  >;
}
