/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1ProvidersMutationRequest,
  PostV1ProvidersMutationResponse,
  PostV1Providers400,
  PostV1Providers409,
  PostV1Providers500
} from '../types/PostV1Providers.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1Providers } from '../clients/postV1Providers.ts';

export const postV1ProvidersMutationKey = () =>
  [{ url: '/v1/providers' }] as const;

export type PostV1ProvidersMutationKey = ReturnType<
  typeof postV1ProvidersMutationKey
>;

export function postV1ProvidersMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1ProvidersMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = postV1ProvidersMutationKey();
  return mutationOptions<
    PostV1ProvidersMutationResponse,
    ResponseErrorConfig<
      PostV1Providers400 | PostV1Providers409 | PostV1Providers500
    >,
    { data: PostV1ProvidersMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1Providers(data, config);
    }
  });
}

/**
 * {@link /v1/providers}
 */
export function usePostV1Providers<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1ProvidersMutationResponse,
      ResponseErrorConfig<
        PostV1Providers400 | PostV1Providers409 | PostV1Providers500
      >,
      { data: PostV1ProvidersMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostV1ProvidersMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1ProvidersMutationKey();

  const baseOptions = postV1ProvidersMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1ProvidersMutationResponse,
    ResponseErrorConfig<
      PostV1Providers400 | PostV1Providers409 | PostV1Providers500
    >,
    { data: PostV1ProvidersMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1ProvidersMutationResponse,
    ResponseErrorConfig<
      PostV1Providers400 | PostV1Providers409 | PostV1Providers500
    >,
    { data: PostV1ProvidersMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1ProvidersMutationResponse,
    ResponseErrorConfig<
      PostV1Providers400 | PostV1Providers409 | PostV1Providers500
    >,
    { data: PostV1ProvidersMutationRequest },
    TContext
  >;
}
