/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1ProcessingMonthsMutationRequest,
  PostV1ProcessingMonthsMutationResponse,
  PostV1ProcessingMonths400,
  PostV1ProcessingMonths500
} from '../types/PostV1ProcessingMonths.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1ProcessingMonths } from '../clients/postV1ProcessingMonths.ts';

export const postV1ProcessingMonthsMutationKey = () =>
  [{ url: '/v1/processing-months' }] as const;

export type PostV1ProcessingMonthsMutationKey = ReturnType<
  typeof postV1ProcessingMonthsMutationKey
>;

export function postV1ProcessingMonthsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1ProcessingMonthsMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = postV1ProcessingMonthsMutationKey();
  return mutationOptions<
    PostV1ProcessingMonthsMutationResponse,
    ResponseErrorConfig<PostV1ProcessingMonths400 | PostV1ProcessingMonths500>,
    { data: PostV1ProcessingMonthsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1ProcessingMonths(data, config);
    }
  });
}

/**
 * {@link /v1/processing-months}
 */
export function usePostV1ProcessingMonths<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1ProcessingMonthsMutationResponse,
      ResponseErrorConfig<
        PostV1ProcessingMonths400 | PostV1ProcessingMonths500
      >,
      { data: PostV1ProcessingMonthsMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostV1ProcessingMonthsMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1ProcessingMonthsMutationKey();

  const baseOptions = postV1ProcessingMonthsMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1ProcessingMonthsMutationResponse,
    ResponseErrorConfig<PostV1ProcessingMonths400 | PostV1ProcessingMonths500>,
    { data: PostV1ProcessingMonthsMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1ProcessingMonthsMutationResponse,
    ResponseErrorConfig<PostV1ProcessingMonths400 | PostV1ProcessingMonths500>,
    { data: PostV1ProcessingMonthsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1ProcessingMonthsMutationResponse,
    ResponseErrorConfig<PostV1ProcessingMonths400 | PostV1ProcessingMonths500>,
    { data: PostV1ProcessingMonthsMutationRequest },
    TContext
  >;
}
