/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1ProviderInvoicesMutationRequest,
  PostV1ProviderInvoicesMutationResponse,
  PostV1ProviderInvoices400,
  PostV1ProviderInvoices500
} from '../types/PostV1ProviderInvoices.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1ProviderInvoices } from '../clients/postV1ProviderInvoices.ts';

export const postV1ProviderInvoicesMutationKey = () =>
  [{ url: '/v1/provider-invoices' }] as const;

export type PostV1ProviderInvoicesMutationKey = ReturnType<
  typeof postV1ProviderInvoicesMutationKey
>;

export function postV1ProviderInvoicesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1ProviderInvoicesMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = postV1ProviderInvoicesMutationKey();
  return mutationOptions<
    PostV1ProviderInvoicesMutationResponse,
    ResponseErrorConfig<PostV1ProviderInvoices400 | PostV1ProviderInvoices500>,
    { data: PostV1ProviderInvoicesMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1ProviderInvoices(data, config);
    }
  });
}

/**
 * {@link /v1/provider-invoices}
 */
export function usePostV1ProviderInvoices<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1ProviderInvoicesMutationResponse,
      ResponseErrorConfig<
        PostV1ProviderInvoices400 | PostV1ProviderInvoices500
      >,
      { data: PostV1ProviderInvoicesMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostV1ProviderInvoicesMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1ProviderInvoicesMutationKey();

  const baseOptions = postV1ProviderInvoicesMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1ProviderInvoicesMutationResponse,
    ResponseErrorConfig<PostV1ProviderInvoices400 | PostV1ProviderInvoices500>,
    { data: PostV1ProviderInvoicesMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1ProviderInvoicesMutationResponse,
    ResponseErrorConfig<PostV1ProviderInvoices400 | PostV1ProviderInvoices500>,
    { data: PostV1ProviderInvoicesMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1ProviderInvoicesMutationResponse,
    ResponseErrorConfig<PostV1ProviderInvoices400 | PostV1ProviderInvoices500>,
    { data: PostV1ProviderInvoicesMutationRequest },
    TContext
  >;
}
