/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1CustomersIdAttachmentsMutationRequest,
  PostV1CustomersIdAttachmentsMutationResponse,
  PostV1CustomersIdAttachmentsPathParams,
  PostV1CustomersIdAttachments400,
  PostV1CustomersIdAttachments404,
  PostV1CustomersIdAttachments500
} from '../types/PostV1CustomersIdAttachments.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1CustomersIdAttachments } from '../clients/postV1CustomersIdAttachments.ts';

export const postV1CustomersIdAttachmentsMutationKey = () =>
  [{ url: '/v1/customers/:id/attachments' }] as const;

export type PostV1CustomersIdAttachmentsMutationKey = ReturnType<
  typeof postV1CustomersIdAttachmentsMutationKey
>;

export function postV1CustomersIdAttachmentsMutationOptions<TContext = unknown>(
  config: Partial<
    RequestConfig<PostV1CustomersIdAttachmentsMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey = postV1CustomersIdAttachmentsMutationKey();
  return mutationOptions<
    PostV1CustomersIdAttachmentsMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdAttachments400
      | PostV1CustomersIdAttachments404
      | PostV1CustomersIdAttachments500
    >,
    {
      id: PostV1CustomersIdAttachmentsPathParams['id'];
      data: PostV1CustomersIdAttachmentsMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postV1CustomersIdAttachments(id, data, config);
    }
  });
}

/**
 * {@link /v1/customers/:id/attachments}
 */
export function usePostV1CustomersIdAttachments<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1CustomersIdAttachmentsMutationResponse,
      ResponseErrorConfig<
        | PostV1CustomersIdAttachments400
        | PostV1CustomersIdAttachments404
        | PostV1CustomersIdAttachments500
      >,
      {
        id: PostV1CustomersIdAttachmentsPathParams['id'];
        data: PostV1CustomersIdAttachmentsMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1CustomersIdAttachmentsMutationRequest>
    > & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1CustomersIdAttachmentsMutationKey();

  const baseOptions = postV1CustomersIdAttachmentsMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1CustomersIdAttachmentsMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdAttachments400
      | PostV1CustomersIdAttachments404
      | PostV1CustomersIdAttachments500
    >,
    {
      id: PostV1CustomersIdAttachmentsPathParams['id'];
      data: PostV1CustomersIdAttachmentsMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostV1CustomersIdAttachmentsMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdAttachments400
      | PostV1CustomersIdAttachments404
      | PostV1CustomersIdAttachments500
    >,
    {
      id: PostV1CustomersIdAttachmentsPathParams['id'];
      data: PostV1CustomersIdAttachmentsMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1CustomersIdAttachmentsMutationResponse,
    ResponseErrorConfig<
      | PostV1CustomersIdAttachments400
      | PostV1CustomersIdAttachments404
      | PostV1CustomersIdAttachments500
    >,
    {
      id: PostV1CustomersIdAttachmentsPathParams['id'];
      data: PostV1CustomersIdAttachmentsMutationRequest;
    },
    TContext
  >;
}
