/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1PreSignedUrlsUploadMutationRequest,
  PostV1PreSignedUrlsUploadMutationResponse,
  PostV1PreSignedUrlsUpload400,
  PostV1PreSignedUrlsUpload500
} from '../types/PostV1PreSignedUrlsUpload.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1PreSignedUrlsUpload } from '../clients/postV1PreSignedUrlsUpload.ts';

export const postV1PreSignedUrlsUploadMutationKey = () =>
  [{ url: '/v1/pre-signed-urls/upload' }] as const;

export type PostV1PreSignedUrlsUploadMutationKey = ReturnType<
  typeof postV1PreSignedUrlsUploadMutationKey
>;

export function postV1PreSignedUrlsUploadMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1PreSignedUrlsUploadMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = postV1PreSignedUrlsUploadMutationKey();
  return mutationOptions<
    PostV1PreSignedUrlsUploadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsUpload400 | PostV1PreSignedUrlsUpload500
    >,
    { data: PostV1PreSignedUrlsUploadMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1PreSignedUrlsUpload(data, config);
    }
  });
}

/**
 * {@link /v1/pre-signed-urls/upload}
 */
export function usePostV1PreSignedUrlsUpload<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1PreSignedUrlsUploadMutationResponse,
      ResponseErrorConfig<
        PostV1PreSignedUrlsUpload400 | PostV1PreSignedUrlsUpload500
      >,
      { data: PostV1PreSignedUrlsUploadMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1PreSignedUrlsUploadMutationRequest>
    > & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1PreSignedUrlsUploadMutationKey();

  const baseOptions = postV1PreSignedUrlsUploadMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1PreSignedUrlsUploadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsUpload400 | PostV1PreSignedUrlsUpload500
    >,
    { data: PostV1PreSignedUrlsUploadMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1PreSignedUrlsUploadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsUpload400 | PostV1PreSignedUrlsUpload500
    >,
    { data: PostV1PreSignedUrlsUploadMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1PreSignedUrlsUploadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsUpload400 | PostV1PreSignedUrlsUpload500
    >,
    { data: PostV1PreSignedUrlsUploadMutationRequest },
    TContext
  >;
}
