/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1PreSignedUrlsDownloadMutationRequest,
  PostV1PreSignedUrlsDownloadMutationResponse,
  PostV1PreSignedUrlsDownload400,
  PostV1PreSignedUrlsDownload500
} from '../types/PostV1PreSignedUrlsDownload.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1PreSignedUrlsDownload } from '../clients/postV1PreSignedUrlsDownload.ts';

export const postV1PreSignedUrlsDownloadMutationKey = () =>
  [{ url: '/v1/pre-signed-urls/download' }] as const;

export type PostV1PreSignedUrlsDownloadMutationKey = ReturnType<
  typeof postV1PreSignedUrlsDownloadMutationKey
>;

export function postV1PreSignedUrlsDownloadMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1PreSignedUrlsDownloadMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = postV1PreSignedUrlsDownloadMutationKey();
  return mutationOptions<
    PostV1PreSignedUrlsDownloadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsDownload400 | PostV1PreSignedUrlsDownload500
    >,
    { data: PostV1PreSignedUrlsDownloadMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1PreSignedUrlsDownload(data, config);
    }
  });
}

/**
 * {@link /v1/pre-signed-urls/download}
 */
export function usePostV1PreSignedUrlsDownload<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1PreSignedUrlsDownloadMutationResponse,
      ResponseErrorConfig<
        PostV1PreSignedUrlsDownload400 | PostV1PreSignedUrlsDownload500
      >,
      { data: PostV1PreSignedUrlsDownloadMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1PreSignedUrlsDownloadMutationRequest>
    > & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1PreSignedUrlsDownloadMutationKey();

  const baseOptions = postV1PreSignedUrlsDownloadMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1PreSignedUrlsDownloadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsDownload400 | PostV1PreSignedUrlsDownload500
    >,
    { data: PostV1PreSignedUrlsDownloadMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1PreSignedUrlsDownloadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsDownload400 | PostV1PreSignedUrlsDownload500
    >,
    { data: PostV1PreSignedUrlsDownloadMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1PreSignedUrlsDownloadMutationResponse,
    ResponseErrorConfig<
      PostV1PreSignedUrlsDownload400 | PostV1PreSignedUrlsDownload500
    >,
    { data: PostV1PreSignedUrlsDownloadMutationRequest },
    TContext
  >;
}
