/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1PhoneLinesIdCustomerLinksMutationRequest,
  PostV1PhoneLinesIdCustomerLinksMutationResponse,
  PostV1PhoneLinesIdCustomerLinksPathParams,
  PostV1PhoneLinesIdCustomerLinks400,
  PostV1PhoneLinesIdCustomerLinks404,
  PostV1PhoneLinesIdCustomerLinks409,
  PostV1PhoneLinesIdCustomerLinks500
} from '../types/PostV1PhoneLinesIdCustomerLinks.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1PhoneLinesIdCustomerLinks } from '../clients/postV1PhoneLinesIdCustomerLinks.ts';

export const postV1PhoneLinesIdCustomerLinksMutationKey = () =>
  [{ url: '/v1/phone-lines/:id/customer-links' }] as const;

export type PostV1PhoneLinesIdCustomerLinksMutationKey = ReturnType<
  typeof postV1PhoneLinesIdCustomerLinksMutationKey
>;

export function postV1PhoneLinesIdCustomerLinksMutationOptions<
  TContext = unknown
>(
  config: Partial<
    RequestConfig<PostV1PhoneLinesIdCustomerLinksMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey = postV1PhoneLinesIdCustomerLinksMutationKey();
  return mutationOptions<
    PostV1PhoneLinesIdCustomerLinksMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinks400
      | PostV1PhoneLinesIdCustomerLinks404
      | PostV1PhoneLinesIdCustomerLinks409
      | PostV1PhoneLinesIdCustomerLinks500
    >,
    {
      id: PostV1PhoneLinesIdCustomerLinksPathParams['id'];
      data: PostV1PhoneLinesIdCustomerLinksMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postV1PhoneLinesIdCustomerLinks(id, data, config);
    }
  });
}

/**
 * {@link /v1/phone-lines/:id/customer-links}
 */
export function usePostV1PhoneLinesIdCustomerLinks<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1PhoneLinesIdCustomerLinksMutationResponse,
      ResponseErrorConfig<
        | PostV1PhoneLinesIdCustomerLinks400
        | PostV1PhoneLinesIdCustomerLinks404
        | PostV1PhoneLinesIdCustomerLinks409
        | PostV1PhoneLinesIdCustomerLinks500
      >,
      {
        id: PostV1PhoneLinesIdCustomerLinksPathParams['id'];
        data: PostV1PhoneLinesIdCustomerLinksMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1PhoneLinesIdCustomerLinksMutationRequest>
    > & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1PhoneLinesIdCustomerLinksMutationKey();

  const baseOptions = postV1PhoneLinesIdCustomerLinksMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1PhoneLinesIdCustomerLinksMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinks400
      | PostV1PhoneLinesIdCustomerLinks404
      | PostV1PhoneLinesIdCustomerLinks409
      | PostV1PhoneLinesIdCustomerLinks500
    >,
    {
      id: PostV1PhoneLinesIdCustomerLinksPathParams['id'];
      data: PostV1PhoneLinesIdCustomerLinksMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostV1PhoneLinesIdCustomerLinksMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinks400
      | PostV1PhoneLinesIdCustomerLinks404
      | PostV1PhoneLinesIdCustomerLinks409
      | PostV1PhoneLinesIdCustomerLinks500
    >,
    {
      id: PostV1PhoneLinesIdCustomerLinksPathParams['id'];
      data: PostV1PhoneLinesIdCustomerLinksMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1PhoneLinesIdCustomerLinksMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinks400
      | PostV1PhoneLinesIdCustomerLinks404
      | PostV1PhoneLinesIdCustomerLinks409
      | PostV1PhoneLinesIdCustomerLinks500
    >,
    {
      id: PostV1PhoneLinesIdCustomerLinksPathParams['id'];
      data: PostV1PhoneLinesIdCustomerLinksMutationRequest;
    },
    TContext
  >;
}
