/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PatchV1ProvidersIdMutationRequest,
  PatchV1ProvidersIdMutationResponse,
  PatchV1ProvidersIdPathParams,
  PatchV1ProvidersId400,
  PatchV1ProvidersId404,
  PatchV1ProvidersId409,
  PatchV1ProvidersId500
} from '../types/PatchV1ProvidersId.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { patchV1ProvidersId } from '../clients/patchV1ProvidersId.ts';

export const patchV1ProvidersIdMutationKey = () =>
  [{ url: '/v1/providers/:id' }] as const;

export type PatchV1ProvidersIdMutationKey = ReturnType<
  typeof patchV1ProvidersIdMutationKey
>;

export function patchV1ProvidersIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchV1ProvidersIdMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const mutationKey = patchV1ProvidersIdMutationKey();
  return mutationOptions<
    PatchV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1ProvidersId400
      | PatchV1ProvidersId404
      | PatchV1ProvidersId409
      | PatchV1ProvidersId500
    >,
    {
      id: PatchV1ProvidersIdPathParams['id'];
      data: PatchV1ProvidersIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchV1ProvidersId(id, data, config);
    }
  });
}

/**
 * {@link /v1/providers/:id}
 */
export function usePatchV1ProvidersId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchV1ProvidersIdMutationResponse,
      ResponseErrorConfig<
        | PatchV1ProvidersId400
        | PatchV1ProvidersId404
        | PatchV1ProvidersId409
        | PatchV1ProvidersId500
      >,
      {
        id: PatchV1ProvidersIdPathParams['id'];
        data: PatchV1ProvidersIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchV1ProvidersIdMutationRequest>> & {
      client?: Client;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchV1ProvidersIdMutationKey();

  const baseOptions = patchV1ProvidersIdMutationOptions(
    config
  ) as UseMutationOptions<
    PatchV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1ProvidersId400
      | PatchV1ProvidersId404
      | PatchV1ProvidersId409
      | PatchV1ProvidersId500
    >,
    {
      id: PatchV1ProvidersIdPathParams['id'];
      data: PatchV1ProvidersIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1ProvidersId400
      | PatchV1ProvidersId404
      | PatchV1ProvidersId409
      | PatchV1ProvidersId500
    >,
    {
      id: PatchV1ProvidersIdPathParams['id'];
      data: PatchV1ProvidersIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PatchV1ProvidersIdMutationResponse,
    ResponseErrorConfig<
      | PatchV1ProvidersId400
      | PatchV1ProvidersId404
      | PatchV1ProvidersId409
      | PatchV1ProvidersId500
    >,
    {
      id: PatchV1ProvidersIdPathParams['id'];
      data: PatchV1ProvidersIdMutationRequest;
    },
    TContext
  >;
}
