/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient
} from '@tanstack/react-query';
import type {
  PostV1PhoneLinesIdCustomerLinksTransferMutationRequest,
  PostV1PhoneLinesIdCustomerLinksTransferMutationResponse,
  PostV1PhoneLinesIdCustomerLinksTransferPathParams,
  PostV1PhoneLinesIdCustomerLinksTransfer400,
  PostV1PhoneLinesIdCustomerLinksTransfer404,
  PostV1PhoneLinesIdCustomerLinksTransfer409,
  PostV1PhoneLinesIdCustomerLinksTransfer500
} from '../types/PostV1PhoneLinesIdCustomerLinksTransfer.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { postV1PhoneLinesIdCustomerLinksTransfer } from '../clients/postV1PhoneLinesIdCustomerLinksTransfer.ts';

export const postV1PhoneLinesIdCustomerLinksTransferMutationKey = () =>
  [{ url: '/v1/phone-lines/:id/customer-links/transfer' }] as const;

export type PostV1PhoneLinesIdCustomerLinksTransferMutationKey = ReturnType<
  typeof postV1PhoneLinesIdCustomerLinksTransferMutationKey
>;

export function postV1PhoneLinesIdCustomerLinksTransferMutationOptions<
  TContext = unknown
>(
  config: Partial<
    RequestConfig<PostV1PhoneLinesIdCustomerLinksTransferMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey = postV1PhoneLinesIdCustomerLinksTransferMutationKey();
  return mutationOptions<
    PostV1PhoneLinesIdCustomerLinksTransferMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinksTransfer400
      | PostV1PhoneLinesIdCustomerLinksTransfer404
      | PostV1PhoneLinesIdCustomerLinksTransfer409
      | PostV1PhoneLinesIdCustomerLinksTransfer500
    >,
    {
      id: PostV1PhoneLinesIdCustomerLinksTransferPathParams['id'];
      data: PostV1PhoneLinesIdCustomerLinksTransferMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postV1PhoneLinesIdCustomerLinksTransfer(id, data, config);
    }
  });
}

/**
 * {@link /v1/phone-lines/:id/customer-links/transfer}
 */
export function usePostV1PhoneLinesIdCustomerLinksTransfer<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1PhoneLinesIdCustomerLinksTransferMutationResponse,
      ResponseErrorConfig<
        | PostV1PhoneLinesIdCustomerLinksTransfer400
        | PostV1PhoneLinesIdCustomerLinksTransfer404
        | PostV1PhoneLinesIdCustomerLinksTransfer409
        | PostV1PhoneLinesIdCustomerLinksTransfer500
      >,
      {
        id: PostV1PhoneLinesIdCustomerLinksTransferPathParams['id'];
        data: PostV1PhoneLinesIdCustomerLinksTransferMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1PhoneLinesIdCustomerLinksTransferMutationRequest>
    > & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postV1PhoneLinesIdCustomerLinksTransferMutationKey();

  const baseOptions = postV1PhoneLinesIdCustomerLinksTransferMutationOptions(
    config
  ) as UseMutationOptions<
    PostV1PhoneLinesIdCustomerLinksTransferMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinksTransfer400
      | PostV1PhoneLinesIdCustomerLinksTransfer404
      | PostV1PhoneLinesIdCustomerLinksTransfer409
      | PostV1PhoneLinesIdCustomerLinksTransfer500
    >,
    {
      id: PostV1PhoneLinesIdCustomerLinksTransferPathParams['id'];
      data: PostV1PhoneLinesIdCustomerLinksTransferMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostV1PhoneLinesIdCustomerLinksTransferMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinksTransfer400
      | PostV1PhoneLinesIdCustomerLinksTransfer404
      | PostV1PhoneLinesIdCustomerLinksTransfer409
      | PostV1PhoneLinesIdCustomerLinksTransfer500
    >,
    {
      id: PostV1PhoneLinesIdCustomerLinksTransferPathParams['id'];
      data: PostV1PhoneLinesIdCustomerLinksTransferMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostV1PhoneLinesIdCustomerLinksTransferMutationResponse,
    ResponseErrorConfig<
      | PostV1PhoneLinesIdCustomerLinksTransfer400
      | PostV1PhoneLinesIdCustomerLinksTransfer404
      | PostV1PhoneLinesIdCustomerLinksTransfer409
      | PostV1PhoneLinesIdCustomerLinksTransfer500
    >,
    {
      id: PostV1PhoneLinesIdCustomerLinksTransferPathParams['id'];
      data: PostV1PhoneLinesIdCustomerLinksTransferMutationRequest;
    },
    TContext
  >;
}
