/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  PhoneLinesControllerGetByIdQueryResponse,
  PhoneLinesControllerGetByIdPathParams,
  PhoneLinesControllerGetById404,
  PhoneLinesControllerGetById500
} from '../../types/phoneLinesController/GetById.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { phoneLinesControllerGetById } from '../../clients/phoneLinesController/getById.ts';

export const phoneLinesControllerGetByIdQueryKey = (
  id: PhoneLinesControllerGetByIdPathParams['id']
) => [{ url: '/v1/phone-lines/:id', params: { id: id } }] as const;

export type PhoneLinesControllerGetByIdQueryKey = ReturnType<
  typeof phoneLinesControllerGetByIdQueryKey
>;

export function phoneLinesControllerGetByIdQueryOptions(
  id: PhoneLinesControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = phoneLinesControllerGetByIdQueryKey(id);
  return queryOptions<
    PhoneLinesControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      PhoneLinesControllerGetById404 | PhoneLinesControllerGetById500
    >,
    PhoneLinesControllerGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return phoneLinesControllerGetById(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/phone-lines/:id}
 */
export function usePhoneLinesControllerGetById<
  TData = PhoneLinesControllerGetByIdQueryResponse,
  TQueryData = PhoneLinesControllerGetByIdQueryResponse,
  TQueryKey extends QueryKey = PhoneLinesControllerGetByIdQueryKey
>(
  id: PhoneLinesControllerGetByIdPathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        PhoneLinesControllerGetByIdQueryResponse,
        ResponseErrorConfig<
          PhoneLinesControllerGetById404 | PhoneLinesControllerGetById500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? phoneLinesControllerGetByIdQueryKey(id);

  const query = useQuery(
    {
      ...phoneLinesControllerGetByIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      PhoneLinesControllerGetById404 | PhoneLinesControllerGetById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
