/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  PhoneLinesControllerGetByIdQueryResponse,
  PhoneLinesControllerGetByIdPathParams,
  PhoneLinesControllerGetById404,
  PhoneLinesControllerGetById500
} from '../../types/phoneLinesController/GetById.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { phoneLinesControllerGetById } from '../../clients/phoneLinesController/getById.ts';

export const phoneLinesControllerGetByIdSuspenseQueryKey = (
  id: PhoneLinesControllerGetByIdPathParams['id']
) => [{ url: '/v1/phone-lines/:id', params: { id: id } }] as const;

export type PhoneLinesControllerGetByIdSuspenseQueryKey = ReturnType<
  typeof phoneLinesControllerGetByIdSuspenseQueryKey
>;

export function phoneLinesControllerGetByIdSuspenseQueryOptions(
  id: PhoneLinesControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = phoneLinesControllerGetByIdSuspenseQueryKey(id);
  return queryOptions<
    PhoneLinesControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      PhoneLinesControllerGetById404 | PhoneLinesControllerGetById500
    >,
    PhoneLinesControllerGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return phoneLinesControllerGetById(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/phone-lines/:id}
 */
export function usePhoneLinesControllerGetByIdSuspense<
  TData = PhoneLinesControllerGetByIdQueryResponse,
  TQueryKey extends QueryKey = PhoneLinesControllerGetByIdSuspenseQueryKey
>(
  id: PhoneLinesControllerGetByIdPathParams['id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        PhoneLinesControllerGetByIdQueryResponse,
        ResponseErrorConfig<
          PhoneLinesControllerGetById404 | PhoneLinesControllerGetById500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    phoneLinesControllerGetByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...phoneLinesControllerGetByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      PhoneLinesControllerGetById404 | PhoneLinesControllerGetById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
