/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  ProvidersControllerGetByIdQueryResponse,
  ProvidersControllerGetByIdPathParams,
  ProvidersControllerGetById404,
  ProvidersControllerGetById500
} from '../../types/providersController/GetById.ts';

function getProvidersControllerGetByIdUrl(
  id: ProvidersControllerGetByIdPathParams['id']
) {
  const res = { method: 'GET', url: `/v1/providers/${id}` as const };
  return res;
}

/**
 * {@link /v1/providers/:id}
 */
export async function providersControllerGetById(
  id: ProvidersControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ProvidersControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      ProvidersControllerGetById404 | ProvidersControllerGetById500
    >,
    unknown
  >({
    method: 'GET',
    url: getProvidersControllerGetByIdUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
