/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  BillingCyclesControllerGetByIdQueryResponse,
  BillingCyclesControllerGetByIdPathParams,
  BillingCyclesControllerGetById404,
  BillingCyclesControllerGetById500
} from '../../types/billingCyclesController/GetById.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { billingCyclesControllerGetById } from '../../clients/billingCyclesController/getById.ts';

export const billingCyclesControllerGetByIdSuspenseQueryKey = (
  id: BillingCyclesControllerGetByIdPathParams['id']
) => [{ url: '/v1/billing-cycles/:id', params: { id: id } }] as const;

export type BillingCyclesControllerGetByIdSuspenseQueryKey = ReturnType<
  typeof billingCyclesControllerGetByIdSuspenseQueryKey
>;

export function billingCyclesControllerGetByIdSuspenseQueryOptions(
  id: BillingCyclesControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = billingCyclesControllerGetByIdSuspenseQueryKey(id);
  return queryOptions<
    BillingCyclesControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      BillingCyclesControllerGetById404 | BillingCyclesControllerGetById500
    >,
    BillingCyclesControllerGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return billingCyclesControllerGetById(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/billing-cycles/:id}
 */
export function useBillingCyclesControllerGetByIdSuspense<
  TData = BillingCyclesControllerGetByIdQueryResponse,
  TQueryKey extends QueryKey = BillingCyclesControllerGetByIdSuspenseQueryKey
>(
  id: BillingCyclesControllerGetByIdPathParams['id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        BillingCyclesControllerGetByIdQueryResponse,
        ResponseErrorConfig<
          BillingCyclesControllerGetById404 | BillingCyclesControllerGetById500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    billingCyclesControllerGetByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...billingCyclesControllerGetByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      BillingCyclesControllerGetById404 | BillingCyclesControllerGetById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
