/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from '../ApiResponse.ts';
import type { GetProviderResponse } from '../GetProviderResponse.ts';

export type ProvidersControllerGetByIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type ProvidersControllerGetById200 = GetProviderResponse;

/**
 * @description Not Found
 */
export type ProvidersControllerGetById404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type ProvidersControllerGetById500 = ApiResponse;

export type ProvidersControllerGetByIdQueryResponse =
  ProvidersControllerGetById200;

export type ProvidersControllerGetByIdQuery = {
  Response: ProvidersControllerGetById200;
  PathParams: ProvidersControllerGetByIdPathParams;
  Errors: ProvidersControllerGetById404 | ProvidersControllerGetById500;
};
