/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import type {
  ProvidersControllerGetByIdQueryResponse,
  ProvidersControllerGetByIdPathParams,
  ProvidersControllerGetById404,
  ProvidersControllerGetById500
} from '../../types/providersController/GetById.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { providersControllerGetById } from '../../clients/providersController/getById.ts';

export const providersControllerGetByIdQueryKey = (
  id: ProvidersControllerGetByIdPathParams['id']
) => [{ url: '/v1/providers/:id', params: { id: id } }] as const;

export type ProvidersControllerGetByIdQueryKey = ReturnType<
  typeof providersControllerGetByIdQueryKey
>;

export function providersControllerGetByIdQueryOptions(
  id: ProvidersControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = providersControllerGetByIdQueryKey(id);
  return queryOptions<
    ProvidersControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      ProvidersControllerGetById404 | ProvidersControllerGetById500
    >,
    ProvidersControllerGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return providersControllerGetById(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/providers/:id}
 */
export function useProvidersControllerGetById<
  TData = ProvidersControllerGetByIdQueryResponse,
  TQueryData = ProvidersControllerGetByIdQueryResponse,
  TQueryKey extends QueryKey = ProvidersControllerGetByIdQueryKey
>(
  id: ProvidersControllerGetByIdPathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        ProvidersControllerGetByIdQueryResponse,
        ResponseErrorConfig<
          ProvidersControllerGetById404 | ProvidersControllerGetById500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? providersControllerGetByIdQueryKey(id);

  const query = useQuery(
    {
      ...providersControllerGetByIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      ProvidersControllerGetById404 | ProvidersControllerGetById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
