/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import type {
  ProvidersControllerGetByIdQueryResponse,
  ProvidersControllerGetByIdPathParams,
  ProvidersControllerGetById404,
  ProvidersControllerGetById500
} from '../../types/providersController/GetById.ts';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import { providersControllerGetById } from '../../clients/providersController/getById.ts';

export const providersControllerGetByIdSuspenseQueryKey = (
  id: ProvidersControllerGetByIdPathParams['id']
) => [{ url: '/v1/providers/:id', params: { id: id } }] as const;

export type ProvidersControllerGetByIdSuspenseQueryKey = ReturnType<
  typeof providersControllerGetByIdSuspenseQueryKey
>;

export function providersControllerGetByIdSuspenseQueryOptions(
  id: ProvidersControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = providersControllerGetByIdSuspenseQueryKey(id);
  return queryOptions<
    ProvidersControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      ProvidersControllerGetById404 | ProvidersControllerGetById500
    >,
    ProvidersControllerGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return providersControllerGetById(id, {
        ...config,
        signal: config.signal ?? signal
      });
    }
  });
}

/**
 * {@link /v1/providers/:id}
 */
export function useProvidersControllerGetByIdSuspense<
  TData = ProvidersControllerGetByIdQueryResponse,
  TQueryKey extends QueryKey = ProvidersControllerGetByIdSuspenseQueryKey
>(
  id: ProvidersControllerGetByIdPathParams['id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ProvidersControllerGetByIdQueryResponse,
        ResponseErrorConfig<
          ProvidersControllerGetById404 | ProvidersControllerGetById500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? providersControllerGetByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...providersControllerGetByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      ProvidersControllerGetById404 | ProvidersControllerGetById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
