/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from '../ApiResponse.ts';
import type { GetBillingCycleResponse } from '../GetBillingCycleResponse.ts';

export type BillingCyclesControllerGetByIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type BillingCyclesControllerGetById200 = GetBillingCycleResponse;

/**
 * @description Not Found
 */
export type BillingCyclesControllerGetById404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type BillingCyclesControllerGetById500 = ApiResponse;

export type BillingCyclesControllerGetByIdQueryResponse =
  BillingCyclesControllerGetById200;

export type BillingCyclesControllerGetByIdQuery = {
  Response: BillingCyclesControllerGetById200;
  PathParams: BillingCyclesControllerGetByIdPathParams;
  Errors: BillingCyclesControllerGetById404 | BillingCyclesControllerGetById500;
};
