/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  CustomersControllerGetByIdQueryResponse,
  CustomersControllerGetByIdPathParams,
  CustomersControllerGetById404,
  CustomersControllerGetById500
} from '../../types/customersController/GetById.ts';

function getCustomersControllerGetByIdUrl(
  id: CustomersControllerGetByIdPathParams['id']
) {
  const res = { method: 'GET', url: `/v1/customers/${id}` as const };
  return res;
}

/**
 * {@link /v1/customers/:id}
 */
export async function customersControllerGetById(
  id: CustomersControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CustomersControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      CustomersControllerGetById404 | CustomersControllerGetById500
    >,
    unknown
  >({
    method: 'GET',
    url: getCustomersControllerGetByIdUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
