/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from '../ApiResponse.ts';
import type { GetProviderInvoiceResponse } from '../GetProviderInvoiceResponse.ts';

export type ProviderInvoicesControllerGetByIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type ProviderInvoicesControllerGetById200 = GetProviderInvoiceResponse;

/**
 * @description Not Found
 */
export type ProviderInvoicesControllerGetById404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type ProviderInvoicesControllerGetById500 = ApiResponse;

export type ProviderInvoicesControllerGetByIdQueryResponse =
  ProviderInvoicesControllerGetById200;

export type ProviderInvoicesControllerGetByIdQuery = {
  Response: ProviderInvoicesControllerGetById200;
  PathParams: ProviderInvoicesControllerGetByIdPathParams;
  Errors:
    | ProviderInvoicesControllerGetById404
    | ProviderInvoicesControllerGetById500;
};
