/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  PhoneLinesControllerGetByIdQueryResponse,
  PhoneLinesControllerGetByIdPathParams,
  PhoneLinesControllerGetById404,
  PhoneLinesControllerGetById500
} from '../../types/phoneLinesController/GetById.ts';

function getPhoneLinesControllerGetByIdUrl(
  id: PhoneLinesControllerGetByIdPathParams['id']
) {
  const res = { method: 'GET', url: `/v1/phone-lines/${id}` as const };
  return res;
}

/**
 * {@link /v1/phone-lines/:id}
 */
export async function phoneLinesControllerGetById(
  id: PhoneLinesControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PhoneLinesControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      PhoneLinesControllerGetById404 | PhoneLinesControllerGetById500
    >,
    unknown
  >({
    method: 'GET',
    url: getPhoneLinesControllerGetByIdUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
