/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from '../ApiResponse.ts';
import type { GetProcessingMonthResponse } from '../GetProcessingMonthResponse.ts';

export type ProcessingMonthsControllerGetByIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type ProcessingMonthsControllerGetById200 = GetProcessingMonthResponse;

/**
 * @description Not Found
 */
export type ProcessingMonthsControllerGetById404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type ProcessingMonthsControllerGetById500 = ApiResponse;

export type ProcessingMonthsControllerGetByIdQueryResponse =
  ProcessingMonthsControllerGetById200;

export type ProcessingMonthsControllerGetByIdQuery = {
  Response: ProcessingMonthsControllerGetById200;
  PathParams: ProcessingMonthsControllerGetByIdPathParams;
  Errors:
    | ProcessingMonthsControllerGetById404
    | ProcessingMonthsControllerGetById500;
};
