version: '3.9'

name: luxus-connect

services:
  database:
    container_name: database.connect.luxus
    image: ${REGISTRY:-luxus/connect-database}:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ../../..
      dockerfile: ./infra/docker/develop/database/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    env_file:
      - ./database/.database.env
    volumes:
      - database-vol:/var/lib/pgsql/pgdata
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - connect-luxus-default-net-dev

  rabbitmq:
    container_name: rabbitmq.connect.luxus
    image: ${REGISTRY:-luxus/connect-rabbitmq}:${PLATFORM:-linux}-${TAG:-latest}
    hostname: 'mabbit'
    build:
      context: ../../..
      dockerfile: ./infra/docker/develop/rabbitmq/Dockerfile
    restart: unless-stopped
    env_file:
      - ./rabbitmq/.rabbitmq.env
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
      - rabbitmq-mnesia:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - connect-luxus-default-net-dev

  seq:
    image: ${REGISTRY:-luxus/connect-seq}:${PLATFORM:-linux}-${TAG:-latest}
    container_name: seq.connect.luxus
    build:
      context: ../../..
      dockerfile: ./infra/docker/develop/seq/Dockerfile
    restart: unless-stopped
    env_file:
      - ./seq/.seq.env
    ports:
      - "81:80"
      - "5341:5341"
    volumes:
      - seq-data:/var/lib/seq/data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - connect-luxus-default-net-dev

  backend:
    image: ${REGISTRY:-luxus/connect-backend}:${PLATFORM:-linux}-${TAG:-latest}
    container_name: backend.connect.luxus
    restart: always
    build:
      context: ../../..
      dockerfile: ./infra/docker/develop/backend/Dockerfile
    env_file:
      - ./backend/.backend.env
    ports:
      - '8002:80'
    depends_on:
      - database
    networks:
      - connect-luxus-default-net-dev

  frontend:
    image: ${REGISTRY:-luxus/connect-frontend}:${PLATFORM:-linux}-${TAG:-latest}
    container_name: frontend.connect.luxus
    build:
      context: ../../..
      dockerfile: ./infra/docker/develop/frontend/Dockerfile
    env_file:
      - ./frontend/.frontend.env
    depends_on:
      - backend
    networks:
      - connect-luxus-default-net-dev

  keycloak:
    container_name: keycloak.connect.luxus
    image: ${REGISTRY:-luxus/connect-keycloak}:${PLATFORM:-linux}-${TAG:-latest}
    user: root
    build:
      context: ../../..
      dockerfile: ./infra/docker/develop/keycloak/Dockerfile
    command: [ "start", "--optimized", "--import-realm", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false" ]
    env_file:
      - ./keycloak/.keycloak.env
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ../../../resources/theme/:/opt/keycloak/themes
      - ./keycloak/data/luxus-realm.json:/opt/keycloak/data/import/luxus-realm.json:ro
    ports:
      - "8081:8080"
      - "8443:8443"
    depends_on:
      - database
    networks:
      - connect-luxus-default-net-dev

networks:
  connect-luxus-default-net-dev:
    driver: bridge

volumes:
  database-vol:
    name: connect.luxus.database-vol
  seq-data:
    name: connect.luxus.seq-vol
  keycloak-data:
    name: connect.luxus.keycloak-vol
  rabbitmq-data:
    name: connect.luxus.rabbitmq-data-vol
  rabbitmq-mnesia:
    name: connect.luxus.rabbitmq-mnesia-vol
  rabbitmq-logs:
    name: connect.luxus.rabbitmq-logs
