/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  ProcessingMonthsControllerGetByIdQueryResponse,
  ProcessingMonthsControllerGetByIdPathParams,
  ProcessingMonthsControllerGetById404,
  ProcessingMonthsControllerGetById500
} from '../../types/processingMonthsController/GetById.ts';

function getProcessingMonthsControllerGetByIdUrl(
  id: ProcessingMonthsControllerGetByIdPathParams['id']
) {
  const res = { method: 'GET', url: `/v1/processing-months/${id}` as const };
  return res;
}

/**
 * {@link /v1/processing-months/:id}
 */
export async function processingMonthsControllerGetById(
  id: ProcessingMonthsControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ProcessingMonthsControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      | ProcessingMonthsControllerGetById404
      | ProcessingMonthsControllerGetById500
    >,
    unknown
  >({
    method: 'GET',
    url: getProcessingMonthsControllerGetByIdUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
