/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/client.ts';
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig
} from '@/lib/client.ts';
import type {
  BillingCyclesControllerGetByIdQueryResponse,
  BillingCyclesControllerGetByIdPathParams,
  BillingCyclesControllerGetById404,
  BillingCyclesControllerGetById500
} from '../../types/billingCyclesController/GetById.ts';

function getBillingCyclesControllerGetByIdUrl(
  id: BillingCyclesControllerGetByIdPathParams['id']
) {
  const res = { method: 'GET', url: `/v1/billing-cycles/${id}` as const };
  return res;
}

/**
 * {@link /v1/billing-cycles/:id}
 */
export async function billingCyclesControllerGetById(
  id: BillingCyclesControllerGetByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    BillingCyclesControllerGetByIdQueryResponse,
    ResponseErrorConfig<
      BillingCyclesControllerGetById404 | BillingCyclesControllerGetById500
    >,
    unknown
  >({
    method: 'GET',
    url: getBillingCyclesControllerGetByIdUrl(id).url.toString(),
    ...requestConfig
  });
  return res.data;
}
