/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Notification } from './Notification.ts';

export type ApiResponse = {
  /**
   * @type array | undefined
   */
  messages?: Notification[];
};
