/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateCustomerAddressCommand } from './CreateCustomerAddressCommand.ts';

export type CreateCustomerCommand = {
  /**
   * @type string
   */
  provider_id: string;
  /**
   * @type string
   */
  type: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type null,string
   */
  legal_name?: string | null;
  /**
   * @type string
   */
  document: string;
  /**
   * @type null,string
   */
  state_registration?: string | null;
  /**
   * @type null,string, date
   */
  birth_or_opening_date?: string | null;
  /**
   * @type null,string
   */
  responsible_salesperson_user_id?: string | null;
  /**
   * @type array | undefined
   */
  addresses?: CreateCustomerAddressCommand[];
};
