/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateProviderInput = {
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  slug: string;
};
