/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateCustomerResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type boolean
   */
  active: boolean;
  /**
   * @type string
   */
  type: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  cpf_cnpj: string;
  /**
   * @type null,string
   */
  state_registration: string | null;
  /**
   * @type null,string
   */
  legal_name: string | null;
  /**
   * @type null,string, date
   */
  birth_or_opening_date: string | null;
  /**
   * @type null,string
   */
  responsible_salesperson_user_id: string | null;
};
