/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateCustomerAddressCommand = {
  /**
   * @type string
   */
  street: string;
  /**
   * @type string
   */
  number: string;
  /**
   * @type string
   */
  neighborhood: string;
  /**
   * @type string
   */
  city: string;
  /**
   * @type string
   */
  state: string;
  /**
   * @type string
   */
  zip_code: string;
  /**
   * @type null,string
   */
  complement?: string | null;
  /**
   * @default "Brasil"
   * @type string | undefined
   */
  country?: string;
};
