/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateProcessingMonthInput = {
  /**
   * @type string
   */
  provider_id: string;
  /**
   * @type integer, int32
   */
  year: number;
  /**
   * @type integer, int32
   */
  month: number;
  /**
   * @type string
   */
  display_name: string;
};
