/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreatePresignedDownloadUrlInput = {
  /**
   * @type string
   */
  bucket_name: string;
  /**
   * @type string
   */
  object_key: string;
  /**
   * @type null,integer, int32
   */
  expires_in_seconds?: number | null;
};
