/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CustomerPhoneLineLinkResponse = {
  /**
   * @type string
   */
  customer_id: string;
  /**
   * @type string
   */
  phone_line_id: string;
  /**
   * @type string
   */
  phone_line_number: string;
  /**
   * @type string
   */
  phone_line_status: string;
  /**
   * @type string
   */
  line_classification: string;
  /**
   * @type string, date
   */
  start_date: string;
  /**
   * @type null,string, date
   */
  end_date: string | null;
  /**
   * @type boolean
   */
  is_active: boolean;
};
