/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DashboardStatsResponse = {
  /**
   * @type integer, int32
   */
  billing_cycles_count: number;
  /**
   * @type integer, int32
   */
  customers_count: number;
  /**
   * @type integer, int32
   */
  providers_count: number;
  /**
   * @type integer, int32
   */
  provider_invoices_count: number;
  /**
   * @type integer, int32
   */
  phone_lines_count: number;
};
