/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { UnassignPhoneLineCustomerInput } from './UnassignPhoneLineCustomerInput.ts';

export type DeleteV1PhoneLinesIdCustomerLinksActivePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Accepted
 */
export type DeleteV1PhoneLinesIdCustomerLinksActive202 = any;

/**
 * @description Bad Request
 */
export type DeleteV1PhoneLinesIdCustomerLinksActive400 = ApiResponse;

/**
 * @description Not Found
 */
export type DeleteV1PhoneLinesIdCustomerLinksActive404 = ApiResponse;

/**
 * @description Conflict
 */
export type DeleteV1PhoneLinesIdCustomerLinksActive409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type DeleteV1PhoneLinesIdCustomerLinksActive500 = ApiResponse;

export type DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest =
  UnassignPhoneLineCustomerInput;

export type DeleteV1PhoneLinesIdCustomerLinksActiveMutationResponse =
  DeleteV1PhoneLinesIdCustomerLinksActive202;

export type DeleteV1PhoneLinesIdCustomerLinksActiveMutation = {
  Response: DeleteV1PhoneLinesIdCustomerLinksActive202;
  Request: DeleteV1PhoneLinesIdCustomerLinksActiveMutationRequest;
  PathParams: DeleteV1PhoneLinesIdCustomerLinksActivePathParams;
  Errors:
    | DeleteV1PhoneLinesIdCustomerLinksActive400
    | DeleteV1PhoneLinesIdCustomerLinksActive404
    | DeleteV1PhoneLinesIdCustomerLinksActive409
    | DeleteV1PhoneLinesIdCustomerLinksActive500;
};
