/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';

export type DeleteV1CustomersIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Accepted
 */
export type DeleteV1CustomersId202 = any;

/**
 * @description Bad Request
 */
export type DeleteV1CustomersId400 = ApiResponse;

/**
 * @description Not Found
 */
export type DeleteV1CustomersId404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type DeleteV1CustomersId500 = ApiResponse;

export type DeleteV1CustomersIdMutationResponse = DeleteV1CustomersId202;

export type DeleteV1CustomersIdMutation = {
  Response: DeleteV1CustomersId202;
  PathParams: DeleteV1CustomersIdPathParams;
  Errors:
    | DeleteV1CustomersId400
    | DeleteV1CustomersId404
    | DeleteV1CustomersId500;
};
