/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';

export type DeleteV1ProvidersIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Accepted
 */
export type DeleteV1ProvidersId202 = any;

/**
 * @description Bad Request
 */
export type DeleteV1ProvidersId400 = ApiResponse;

/**
 * @description Not Found
 */
export type DeleteV1ProvidersId404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type DeleteV1ProvidersId500 = ApiResponse;

export type DeleteV1ProvidersIdMutationResponse = DeleteV1ProvidersId202;

export type DeleteV1ProvidersIdMutation = {
  Response: DeleteV1ProvidersId202;
  PathParams: DeleteV1ProvidersIdPathParams;
  Errors:
    | DeleteV1ProvidersId400
    | DeleteV1ProvidersId404
    | DeleteV1ProvidersId500;
};
