/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';

export type DeleteV1CustomersIdAttachmentsAttachmentidPathParams = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  attachmentId: string;
};

/**
 * @description Accepted
 */
export type DeleteV1CustomersIdAttachmentsAttachmentid202 = any;

/**
 * @description Bad Request
 */
export type DeleteV1CustomersIdAttachmentsAttachmentid400 = ApiResponse;

/**
 * @description Not Found
 */
export type DeleteV1CustomersIdAttachmentsAttachmentid404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type DeleteV1CustomersIdAttachmentsAttachmentid500 = ApiResponse;

export type DeleteV1CustomersIdAttachmentsAttachmentidMutationResponse =
  DeleteV1CustomersIdAttachmentsAttachmentid202;

export type DeleteV1CustomersIdAttachmentsAttachmentidMutation = {
  Response: DeleteV1CustomersIdAttachmentsAttachmentid202;
  PathParams: DeleteV1CustomersIdAttachmentsAttachmentidPathParams;
  Errors:
    | DeleteV1CustomersIdAttachmentsAttachmentid400
    | DeleteV1CustomersIdAttachmentsAttachmentid404
    | DeleteV1CustomersIdAttachmentsAttachmentid500;
};
