/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetCustomerProcessingMonthBillingReadinessManualReleaseDto = {
  /**
   * @type string
   */
  justification: string;
  /**
   * @type string, date-time
   */
  released_at: string;
  /**
   * @type string
   */
  released_by_user_id: string;
};
