/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetPhoneLineServiceResponse } from './GetPhoneLineServiceResponse.ts';
import type { GetProviderPlanResponse } from './GetProviderPlanResponse.ts';

export type GetChildPhoneLineResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  provider_plan_id: string;
  /**
   * @type string
   */
  provider_account_id: string;
  /**
   * @type null,string
   */
  cost_center_id: string | null;
  /**
   * @type null,string
   */
  last_invoice_id: string | null;
  /**
   * @type null,string
   */
  titular_line_id: string | null;
  /**
   * @type string
   */
  number: string;
  /**
   * @type string
   */
  line_classification: string;
  /**
   * @type string
   */
  status: string;
  /**
   * @type null,string
   */
  transition_sub_status: string | null;
  /**
   * @type null,string, date-time
   */
  transition_started_at: string | null;
  /**
   * @type null,string, date
   */
  activation_date: string | null;
  /**
   * @type null,string, date
   */
  cancellation_date: string | null;
  /**
   * @type object
   */
  plan: GetProviderPlanResponse;
  /**
   * @type array
   */
  services: GetPhoneLineServiceResponse[];
};
