/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetCustomerProcessingMonthBillingReadinessManualReleaseDto } from './GetCustomerProcessingMonthBillingReadinessManualReleaseDto.ts';

export type GetCustomerProcessingMonthBillingReadinessResponse = {
  /**
   * @type string
   */
  customer_id: string;
  /**
   * @type string
   */
  processing_month_id: string;
  /**
   * @type string
   */
  status_display_name: string;
  /**
   * @type boolean
   */
  is_released_for_billing: boolean;
  /**
   * @type boolean
   */
  is_automatically_complete: boolean;
  /**
   * @type boolean
   */
  is_manually_released: boolean;
  /**
   * @type boolean
   */
  automatic_evaluation_uses_cnpj_contracting_companies: boolean;
  /**
   * @type integer, int32
   */
  accounts_expected_for_automatic_rule: number;
  /**
   * @type integer, int32
   */
  accounts_with_invoice_in_processing_month: number;
  manual_release: null | GetCustomerProcessingMonthBillingReadinessManualReleaseDto;
};
