/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProviderInvoiceQuotaSharingResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  invoice_id: string;
  /**
   * @type string
   */
  phone_line_id: string;
  /**
   * @type string
   */
  description: string;
  /**
   * @type null,number, decimal
   */
  consumed_amount: number | null;
};
