/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProviderPlanServiceResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type boolean
   */
  active: boolean;
  /**
   * @type boolean
   */
  recurring: boolean;
  /**
   * @type null,number, decimal
   */
  price: number | null;
};
