/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetProviderPlanResponse } from './GetProviderPlanResponse.ts';

export type GetProviderResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  organization_id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  slug: string;
  /**
   * @type boolean
   */
  active: boolean;
  /**
   * @type array
   */
  plans: GetProviderPlanResponse[];
};
