/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProviderInvoiceItemResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  invoice_id: string;
  /**
   * @type null,string
   */
  parent_id: string | null;
  /**
   * @type string
   */
  description: string;
  /**
   * @type number, decimal
   */
  quantity: number;
  /**
   * @type number, decimal
   */
  total_price: number;
  /**
   * @type string
   */
  item_type: string;
  /**
   * @type null,number, decimal
   */
  quota_amount: number | null;
  /**
   * @type null,number, decimal
   */
  consumed_amount: number | null;
  /**
   * @type null,string
   */
  unit: string | null;
  /**
   * @type array
   */
  children: GetProviderInvoiceItemResponse[];
};
