/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetPhoneLineServiceResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  phone_line_id: string;
  /**
   * @type string
   */
  provider_plan_service_id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  code: string;
  /**
   * @type boolean
   */
  recurring: boolean;
  /**
   * @type null,number, decimal
   */
  price: number | null;
  /**
   * @type boolean
   */
  active: boolean;
};
