/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetProviderInvoiceItemResponse } from './GetProviderInvoiceItemResponse.ts';
import type { GetProviderInvoiceQuotaSharingResponse } from './GetProviderInvoiceQuotaSharingResponse.ts';
import type { GetProviderInvoiceServiceResponse } from './GetProviderInvoiceServiceResponse.ts';
import type { GetProviderPhoneLineResponse } from './GetProviderPhoneLineResponse.ts';

export type GetProviderInvoiceResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  number: string;
  /**
   * @type string
   */
  provider_account_id: string;
  /**
   * @type string
   */
  provider_account_number: string;
  /**
   * @type string
   */
  contracting_company_id: string;
  /**
   * @type string
   */
  contracting_company_name: string;
  /**
   * @type string
   */
  provider_id: string;
  /**
   * @type string
   */
  provider_name: string;
  /**
   * @type string
   */
  billing_cycle_id: string;
  /**
   * @type string
   */
  billing_cycle_name: string;
  /**
   * @type null,string
   */
  processing_month_id: string | null;
  /**
   * @type null,string
   */
  processing_month_name: string | null;
  /**
   * @type null,string
   */
  cost_center_id: string | null;
  /**
   * @type null,string
   */
  cost_center_name: string | null;
  /**
   * @type null,string
   */
  parent_invoice_id: string | null;
  /**
   * @type string, date
   */
  issue_date: string;
  /**
   * @type string, date
   */
  due_date: string;
  /**
   * @type number, decimal
   */
  total_amount: number;
  /**
   * @type string
   */
  status: string;
  /**
   * @type number, decimal
   */
  subtotal_services: number;
  /**
   * @type number, decimal
   */
  subtotal_usage: number;
  /**
   * @type number, decimal
   */
  subtotal_taxes: number;
  /**
   * @type number, decimal
   */
  subtotal_discounts: number;
  /**
   * @type number, decimal
   */
  subtotal_installments: number;
  account_payable_id?: string | null;
  account_payable_status?: string | null;
  /**
   * @type array
   */
  phone_lines: GetProviderPhoneLineResponse[];
  /**
   * @type array
   */
  provider_invoice_items: GetProviderInvoiceItemResponse[];
  /**
   * @type array
   */
  provider_invoice_services: GetProviderInvoiceServiceResponse[];
  /**
   * @type array
   */
  provider_invoice_quota_sharing: GetProviderInvoiceQuotaSharingResponse[];
};
