/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetProviderPlanServiceResponse } from './GetProviderPlanServiceResponse.ts';

export type GetProviderPlanResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  code: string;
  /**
   * @type array
   */
  services: GetProviderPlanServiceResponse[];
};
