/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProviderInvoiceServiceResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  invoice_id: string;
  /**
   * @type string
   */
  plan_id: string;
  /**
   * @type string
   */
  plan_name: string;
  /**
   * @type string
   */
  description: string;
  /**
   * @type number, decimal
   */
  quantity: number;
  /**
   * @type number, decimal
   */
  total_price: number;
  /**
   * @type null,number, decimal
   */
  quota_amount: number | null;
  /**
   * @type null,number, decimal
   */
  consumed_amount: number | null;
  /**
   * @type null,string
   */
  unit: string | null;
};
