/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PagedResponseOfCustomerPhoneLineLinkResponse } from './PagedResponseOfCustomerPhoneLineLinkResponse.ts';

export type GetV1CustomersIdPhoneLinesPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type GetV1CustomersIdPhoneLinesQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  page_index?: number;
  /**
   * @type integer | undefined, int32
   */
  page_size?: number;
};

/**
 * @description OK
 */
export type GetV1CustomersIdPhoneLines200 =
  PagedResponseOfCustomerPhoneLineLinkResponse;

/**
 * @description Internal Server Error
 */
export type GetV1CustomersIdPhoneLines500 = ApiResponse;

export type GetV1CustomersIdPhoneLinesQueryResponse =
  GetV1CustomersIdPhoneLines200;

export type GetV1CustomersIdPhoneLinesQuery = {
  Response: GetV1CustomersIdPhoneLines200;
  PathParams: GetV1CustomersIdPhoneLinesPathParams;
  QueryParams: GetV1CustomersIdPhoneLinesQueryParams;
  Errors: GetV1CustomersIdPhoneLines500;
};
