/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PagedResponseOfListCostCenterResponse } from './PagedResponseOfListCostCenterResponse.ts';

export type GetV1CostCentersQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  page_index?: number;
  /**
   * @type integer | undefined, int32
   */
  page_size?: number;
};

/**
 * @description OK
 */
export type GetV1CostCenters200 = PagedResponseOfListCostCenterResponse;

/**
 * @description Bad Request
 */
export type GetV1CostCenters400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type GetV1CostCenters500 = ApiResponse;

export type GetV1CostCentersQueryResponse = GetV1CostCenters200;

export type GetV1CostCentersQuery = {
  Response: GetV1CostCenters200;
  QueryParams: GetV1CostCentersQueryParams;
  Errors: GetV1CostCenters400 | GetV1CostCenters500;
};
