/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PagedResponseOfListProcessingMonthResponse } from './PagedResponseOfListProcessingMonthResponse.ts';

export type GetV1ProcessingMonthsQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  page_index?: number;
  /**
   * @type integer | undefined, int32
   */
  page_size?: number;
};

/**
 * @description OK
 */
export type GetV1ProcessingMonths200 =
  PagedResponseOfListProcessingMonthResponse;

/**
 * @description Bad Request
 */
export type GetV1ProcessingMonths400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type GetV1ProcessingMonths500 = ApiResponse;

export type GetV1ProcessingMonthsQueryResponse = GetV1ProcessingMonths200;

export type GetV1ProcessingMonthsQuery = {
  Response: GetV1ProcessingMonths200;
  QueryParams: GetV1ProcessingMonthsQueryParams;
  Errors: GetV1ProcessingMonths400 | GetV1ProcessingMonths500;
};
