/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CustomerAttachmentResponse } from './CustomerAttachmentResponse.ts';

export type GetV1CustomersIdAttachmentsPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type GetV1CustomersIdAttachments200 = CustomerAttachmentResponse[];

/**
 * @description Not Found
 */
export type GetV1CustomersIdAttachments404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type GetV1CustomersIdAttachments500 = ApiResponse;

export type GetV1CustomersIdAttachmentsQueryResponse =
  GetV1CustomersIdAttachments200;

export type GetV1CustomersIdAttachmentsQuery = {
  Response: GetV1CustomersIdAttachments200;
  PathParams: GetV1CustomersIdAttachmentsPathParams;
  Errors: GetV1CustomersIdAttachments404 | GetV1CustomersIdAttachments500;
};
