/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PhoneLineCustomerLinkResponse } from './PhoneLineCustomerLinkResponse.ts';

export type GetV1PhoneLinesIdCustomerLinksPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type GetV1PhoneLinesIdCustomerLinks200 = PhoneLineCustomerLinkResponse[];

/**
 * @description Internal Server Error
 */
export type GetV1PhoneLinesIdCustomerLinks500 = ApiResponse;

export type GetV1PhoneLinesIdCustomerLinksQueryResponse =
  GetV1PhoneLinesIdCustomerLinks200;

export type GetV1PhoneLinesIdCustomerLinksQuery = {
  Response: GetV1PhoneLinesIdCustomerLinks200;
  PathParams: GetV1PhoneLinesIdCustomerLinksPathParams;
  Errors: GetV1PhoneLinesIdCustomerLinks500;
};
