/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CustomerProviderLinkResponse } from './CustomerProviderLinkResponse.ts';

export type GetV1CustomersIdProviderLinksPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type GetV1CustomersIdProviderLinks200 = CustomerProviderLinkResponse[];

/**
 * @description Internal Server Error
 */
export type GetV1CustomersIdProviderLinks500 = ApiResponse;

export type GetV1CustomersIdProviderLinksQueryResponse =
  GetV1CustomersIdProviderLinks200;

export type GetV1CustomersIdProviderLinksQuery = {
  Response: GetV1CustomersIdProviderLinks200;
  PathParams: GetV1CustomersIdProviderLinksPathParams;
  Errors: GetV1CustomersIdProviderLinks500;
};
