/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { GetCustomerProcessingMonthBillingReadinessResponse } from './GetCustomerProcessingMonthBillingReadinessResponse.ts';

export type GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams =
  {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    processingMonthId: string;
  };

/**
 * @description OK
 */
export type GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness200 =
  GetCustomerProcessingMonthBillingReadinessResponse;

/**
 * @description Not Found
 */
export type GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404 =
  ApiResponse;

/**
 * @description Internal Server Error
 */
export type GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500 =
  ApiResponse;

export type GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQueryResponse =
  GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness200;

export type GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessQuery =
  {
    Response: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness200;
    PathParams: GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadinessPathParams;
    Errors:
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness404
      | GetV1CustomersIdProcessingMonthsProcessingmonthidBillingReadiness500;
  };
