/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PagedResponseOfListCustomerResponse } from './PagedResponseOfListCustomerResponse.ts';

export type GetV1CustomersQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  page_index?: number;
  /**
   * @type integer | undefined, int32
   */
  page_size?: number;
  /**
   * @type string | undefined
   */
  provider_id?: string;
};

/**
 * @description OK
 */
export type GetV1Customers200 = PagedResponseOfListCustomerResponse;

/**
 * @description Internal Server Error
 */
export type GetV1Customers500 = ApiResponse;

export type GetV1CustomersQueryResponse = GetV1Customers200;

export type GetV1CustomersQuery = {
  Response: GetV1Customers200;
  QueryParams: GetV1CustomersQueryParams;
  Errors: GetV1Customers500;
};
