/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { DashboardStatsResponse } from './DashboardStatsResponse.ts';

/**
 * @description OK
 */
export type GetV1StatsDashboard200 = DashboardStatsResponse;

/**
 * @description Internal Server Error
 */
export type GetV1StatsDashboard500 = ApiResponse;

export type GetV1StatsDashboardQueryResponse = GetV1StatsDashboard200;

export type GetV1StatsDashboardQuery = {
  Response: GetV1StatsDashboard200;
  Errors: GetV1StatsDashboard500;
};
