/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PagedResponseOfListProvidersResponse } from './PagedResponseOfListProvidersResponse.ts';

export type GetV1ProvidersQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  page_index?: number;
  /**
   * @type integer | undefined, int32
   */
  page_size?: number;
};

/**
 * @description OK
 */
export type GetV1Providers200 = PagedResponseOfListProvidersResponse;

/**
 * @description Bad Request
 */
export type GetV1Providers400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type GetV1Providers500 = ApiResponse;

export type GetV1ProvidersQueryResponse = GetV1Providers200;

export type GetV1ProvidersQuery = {
  Response: GetV1Providers200;
  QueryParams: GetV1ProvidersQueryParams;
  Errors: GetV1Providers400 | GetV1Providers500;
};
