/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PagedResponseOfListProviderInvoiceResponse } from './PagedResponseOfListProviderInvoiceResponse.ts';

export type GetV1ProviderInvoicesQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  page_index?: number;
  /**
   * @type integer | undefined, int32
   */
  page_size?: number;
  /**
   * @type string | undefined
   */
  processing_month_id?: string;
};

/**
 * @description OK
 */
export type GetV1ProviderInvoices200 =
  PagedResponseOfListProviderInvoiceResponse;

/**
 * @description Bad Request
 */
export type GetV1ProviderInvoices400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type GetV1ProviderInvoices500 = ApiResponse;

export type GetV1ProviderInvoicesQueryResponse = GetV1ProviderInvoices200;

export type GetV1ProviderInvoicesQuery = {
  Response: GetV1ProviderInvoices200;
  QueryParams: GetV1ProviderInvoicesQueryParams;
  Errors: GetV1ProviderInvoices400 | GetV1ProviderInvoices500;
};
