/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PagedResponseOfListBillingCycleResponse } from './PagedResponseOfListBillingCycleResponse.ts';

export type GetV1BillingCyclesQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  page_index?: number;
  /**
   * @type integer | undefined, int32
   */
  page_size?: number;
};

/**
 * @description OK
 */
export type GetV1BillingCycles200 = PagedResponseOfListBillingCycleResponse;

/**
 * @description Bad Request
 */
export type GetV1BillingCycles400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type GetV1BillingCycles500 = ApiResponse;

export type GetV1BillingCyclesQueryResponse = GetV1BillingCycles200;

export type GetV1BillingCyclesQuery = {
  Response: GetV1BillingCycles200;
  QueryParams: GetV1BillingCyclesQueryParams;
  Errors: GetV1BillingCycles400 | GetV1BillingCycles500;
};
