/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PagedResponseOfListPhoneLineResponse } from './PagedResponseOfListPhoneLineResponse.ts';

export type GetV1PhoneLinesQueryParams = {
  /**
   * @type integer | undefined, int32
   */
  page_index?: number;
  /**
   * @type integer | undefined, int32
   */
  page_size?: number;
  /**
   * @type string | undefined
   */
  status?: string;
};

/**
 * @description OK
 */
export type GetV1PhoneLines200 = PagedResponseOfListPhoneLineResponse;

/**
 * @description Bad Request
 */
export type GetV1PhoneLines400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type GetV1PhoneLines500 = ApiResponse;

export type GetV1PhoneLinesQueryResponse = GetV1PhoneLines200;

export type GetV1PhoneLinesQuery = {
  Response: GetV1PhoneLines200;
  QueryParams: GetV1PhoneLinesQueryParams;
  Errors: GetV1PhoneLines400 | GetV1PhoneLines500;
};
