/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ListBillingCycleResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  provider_id: string;
  /**
   * @type string
   */
  code: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string, date
   */
  start_date: string;
  /**
   * @type string, date
   */
  end_date: string;
  /**
   * @type string
   */
  status: string;
  /**
   * @type null,string, date-time
   */
  closed_at: string | null;
  /**
   * @type null,string
   */
  closed_by: string | null;
};
