/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ListPhoneLineResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  provider_plan_id: string;
  /**
   * @type string
   */
  provider_plan_name: string;
  /**
   * @type string
   */
  provider_account_id: string;
  /**
   * @type string
   */
  provider_account_number: string;
  /**
   * @type null,string
   */
  cost_center_id: string | null;
  /**
   * @type null,string
   */
  cost_center_name: string | null;
  /**
   * @type null,string
   */
  last_invoice_id: string | null;
  /**
   * @type null,string
   */
  last_invoice_number: string | null;
  /**
   * @type null,string
   */
  titular_line_id: string | null;
  /**
   * @type null,string
   */
  titular_line_number: string | null;
  /**
   * @type string
   */
  number: string;
  /**
   * @type string
   */
  line_classification: string;
  /**
   * @type string
   */
  status: string;
  /**
   * @type null,string
   */
  transition_sub_status: string | null;
  /**
   * @type null,string, date-time
   */
  transition_started_at: string | null;
  /**
   * @type null,string, date
   */
  activation_date: string | null;
  /**
   * @type null,string, date
   */
  cancellation_date: string | null;
  /**
   * @type null,number, decimal
   */
  base_cost: number | null;
  /**
   * @type null,number, decimal
   */
  cost_with_consumption: number | null;
};
