/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ListProcessingMonthResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  provider_id: string;
  /**
   * @type integer, int32
   */
  year: number;
  /**
   * @type integer, int32
   */
  month: number;
  /**
   * @type string
   */
  display_name: string;
  /**
   * @type string
   */
  status: string;
  /**
   * @type null,string, date-time
   */
  closed_at: string | null;
  /**
   * @type null,string
   */
  closed_by: string | null;
  /**
   * @type boolean
   */
  closed_in_contingency: boolean;
};
