/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Notification = {
  /**
   * @type string
   */
  code: string;
  /**
   * @type string
   */
  message: string;
  /**
   * @type null,string
   */
  param?: string | null;
};
