/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CustomerPhoneLineLinkResponse } from './CustomerPhoneLineLinkResponse.ts';

export type PagedResponseOfCustomerPhoneLineLinkResponse = {
  /**
   * @type array | undefined
   */
  items?: CustomerPhoneLineLinkResponse[];
  /**
   * @type integer | undefined, int64
   */
  total_count?: number;
};
