/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListBillingCycleResponse } from './ListBillingCycleResponse.ts';

export type PagedResponseOfListBillingCycleResponse = {
  /**
   * @type array | undefined
   */
  items?: ListBillingCycleResponse[];
  /**
   * @type integer | undefined, int64
   */
  total_count?: number;
};
