/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListCustomerResponse } from './ListCustomerResponse.ts';

export type PagedResponseOfListCustomerResponse = {
  /**
   * @type array | undefined
   */
  items?: ListCustomerResponse[];
  /**
   * @type integer | undefined, int64
   */
  total_count?: number;
};
