/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListProvidersResponse } from './ListProvidersResponse.ts';

export type PagedResponseOfListProvidersResponse = {
  /**
   * @type array | undefined
   */
  items?: ListProvidersResponse[];
  /**
   * @type integer | undefined, int64
   */
  total_count?: number;
};
