/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListProviderInvoiceResponse } from './ListProviderInvoiceResponse.ts';

export type PagedResponseOfListProviderInvoiceResponse = {
  /**
   * @type array | undefined
   */
  items?: ListProviderInvoiceResponse[];
  /**
   * @type integer | undefined, int64
   */
  total_count?: number;
};
