/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListProcessingMonthResponse } from './ListProcessingMonthResponse.ts';

export type PagedResponseOfListProcessingMonthResponse = {
  /**
   * @type array | undefined
   */
  items?: ListProcessingMonthResponse[];
  /**
   * @type integer | undefined, int64
   */
  total_count?: number;
};
