/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListCostCenterResponse } from './ListCostCenterResponse.ts';

export type PagedResponseOfListCostCenterResponse = {
  /**
   * @type array | undefined
   */
  items?: ListCostCenterResponse[];
  /**
   * @type integer | undefined, int64
   */
  total_count?: number;
};
