/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListPhoneLineResponse } from './ListPhoneLineResponse.ts';

export type PagedResponseOfListPhoneLineResponse = {
  /**
   * @type array | undefined
   */
  items?: ListPhoneLineResponse[];
  /**
   * @type integer | undefined, int64
   */
  total_count?: number;
};
