/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { UpdateCustomerInput } from './UpdateCustomerInput.ts';

export type PatchV1CustomersIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Accepted
 */
export type PatchV1CustomersId202 = any;

/**
 * @description Bad Request
 */
export type PatchV1CustomersId400 = ApiResponse;

/**
 * @description Not Found
 */
export type PatchV1CustomersId404 = ApiResponse;

/**
 * @description Conflict
 */
export type PatchV1CustomersId409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PatchV1CustomersId500 = ApiResponse;

export type PatchV1CustomersIdMutationRequest = UpdateCustomerInput;

export type PatchV1CustomersIdMutationResponse = PatchV1CustomersId202;

export type PatchV1CustomersIdMutation = {
  Response: PatchV1CustomersId202;
  Request: PatchV1CustomersIdMutationRequest;
  PathParams: PatchV1CustomersIdPathParams;
  Errors:
    | PatchV1CustomersId400
    | PatchV1CustomersId404
    | PatchV1CustomersId409
    | PatchV1CustomersId500;
};
