/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { UpdateBillingCycleInput } from './UpdateBillingCycleInput.ts';

export type PatchV1BillingCyclesIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Accepted
 */
export type PatchV1BillingCyclesId202 = any;

/**
 * @description Bad Request
 */
export type PatchV1BillingCyclesId400 = ApiResponse;

/**
 * @description Not Found
 */
export type PatchV1BillingCyclesId404 = ApiResponse;

/**
 * @description Conflict
 */
export type PatchV1BillingCyclesId409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PatchV1BillingCyclesId500 = ApiResponse;

export type PatchV1BillingCyclesIdMutationRequest = UpdateBillingCycleInput;

export type PatchV1BillingCyclesIdMutationResponse = PatchV1BillingCyclesId202;

export type PatchV1BillingCyclesIdMutation = {
  Response: PatchV1BillingCyclesId202;
  Request: PatchV1BillingCyclesIdMutationRequest;
  PathParams: PatchV1BillingCyclesIdPathParams;
  Errors:
    | PatchV1BillingCyclesId400
    | PatchV1BillingCyclesId404
    | PatchV1BillingCyclesId409
    | PatchV1BillingCyclesId500;
};
