/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { UpdateProviderInput } from './UpdateProviderInput.ts';

export type PatchV1ProvidersIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Accepted
 */
export type PatchV1ProvidersId202 = any;

/**
 * @description Bad Request
 */
export type PatchV1ProvidersId400 = ApiResponse;

/**
 * @description Not Found
 */
export type PatchV1ProvidersId404 = ApiResponse;

/**
 * @description Conflict
 */
export type PatchV1ProvidersId409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PatchV1ProvidersId500 = ApiResponse;

export type PatchV1ProvidersIdMutationRequest = UpdateProviderInput;

export type PatchV1ProvidersIdMutationResponse = PatchV1ProvidersId202;

export type PatchV1ProvidersIdMutation = {
  Response: PatchV1ProvidersId202;
  Request: PatchV1ProvidersIdMutationRequest;
  PathParams: PatchV1ProvidersIdPathParams;
  Errors:
    | PatchV1ProvidersId400
    | PatchV1ProvidersId404
    | PatchV1ProvidersId409
    | PatchV1ProvidersId500;
};
