/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PhoneLineCustomerLinkResponse = {
  /**
   * @type string
   */
  phone_line_id: string;
  /**
   * @type string
   */
  customer_id: string;
  /**
   * @type string
   */
  customer_name: string;
  /**
   * @type null,string
   */
  customer_document: string | null;
  /**
   * @type string, date
   */
  start_date: string;
  /**
   * @type null,string, date
   */
  end_date: string | null;
  /**
   * @type boolean
   */
  is_active: boolean;
};
