/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { GetCustomerProcessingMonthBillingReadinessResponse } from './GetCustomerProcessingMonthBillingReadinessResponse.ts';
import type { ManuallyReleaseCustomerForProcessingMonthInput } from './ManuallyReleaseCustomerForProcessingMonthInput.ts';

export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams =
  {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    processingMonthId: string;
  };

/**
 * @description OK
 */
export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease200 =
  GetCustomerProcessingMonthBillingReadinessResponse;

/**
 * @description Bad Request
 */
export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400 =
  ApiResponse;

/**
 * @description Not Found
 */
export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404 =
  ApiResponse;

/**
 * @description Conflict
 */
export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409 =
  ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500 =
  ApiResponse;

export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest =
  ManuallyReleaseCustomerForProcessingMonthInput;

export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationResponse =
  PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease200;

export type PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutation =
  {
    Response: PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease200;
    Request: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleaseMutationRequest;
    PathParams: PostV1CustomersIdProcessingMonthsProcessingmonthidManualReleasePathParams;
    Errors:
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease400
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease404
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease409
      | PostV1CustomersIdProcessingMonthsProcessingmonthidManualRelease500;
  };
