/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CreateBillingCycleInput } from './CreateBillingCycleInput.ts';
import type { CreateBillingCycleResponse } from './CreateBillingCycleResponse.ts';

/**
 * @description Created
 */
export type PostV1BillingCycles201 = CreateBillingCycleResponse;

/**
 * @description Bad Request
 */
export type PostV1BillingCycles400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1BillingCycles500 = ApiResponse;

export type PostV1BillingCyclesMutationRequest = CreateBillingCycleInput;

export type PostV1BillingCyclesMutationResponse = PostV1BillingCycles201;

export type PostV1BillingCyclesMutation = {
  Response: PostV1BillingCycles201;
  Request: PostV1BillingCyclesMutationRequest;
  Errors: PostV1BillingCycles400 | PostV1BillingCycles500;
};
