/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CreateProviderInput } from './CreateProviderInput.ts';
import type { CreateProviderResponse } from './CreateProviderResponse.ts';

/**
 * @description Created
 */
export type PostV1Providers201 = CreateProviderResponse;

/**
 * @description Bad Request
 */
export type PostV1Providers400 = ApiResponse;

/**
 * @description Conflict
 */
export type PostV1Providers409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1Providers500 = ApiResponse;

export type PostV1ProvidersMutationRequest = CreateProviderInput;

export type PostV1ProvidersMutationResponse = PostV1Providers201;

export type PostV1ProvidersMutation = {
  Response: PostV1Providers201;
  Request: PostV1ProvidersMutationRequest;
  Errors: PostV1Providers400 | PostV1Providers409 | PostV1Providers500;
};
