/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { PhoneLineCustomerLinkResponse } from './PhoneLineCustomerLinkResponse.ts';
import type { TransferPhoneLineCustomerInput } from './TransferPhoneLineCustomerInput.ts';

export type PostV1PhoneLinesIdCustomerLinksTransferPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type PostV1PhoneLinesIdCustomerLinksTransfer200 =
  PhoneLineCustomerLinkResponse;

/**
 * @description Bad Request
 */
export type PostV1PhoneLinesIdCustomerLinksTransfer400 = ApiResponse;

/**
 * @description Not Found
 */
export type PostV1PhoneLinesIdCustomerLinksTransfer404 = ApiResponse;

/**
 * @description Conflict
 */
export type PostV1PhoneLinesIdCustomerLinksTransfer409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1PhoneLinesIdCustomerLinksTransfer500 = ApiResponse;

export type PostV1PhoneLinesIdCustomerLinksTransferMutationRequest =
  TransferPhoneLineCustomerInput;

export type PostV1PhoneLinesIdCustomerLinksTransferMutationResponse =
  PostV1PhoneLinesIdCustomerLinksTransfer200;

export type PostV1PhoneLinesIdCustomerLinksTransferMutation = {
  Response: PostV1PhoneLinesIdCustomerLinksTransfer200;
  Request: PostV1PhoneLinesIdCustomerLinksTransferMutationRequest;
  PathParams: PostV1PhoneLinesIdCustomerLinksTransferPathParams;
  Errors:
    | PostV1PhoneLinesIdCustomerLinksTransfer400
    | PostV1PhoneLinesIdCustomerLinksTransfer404
    | PostV1PhoneLinesIdCustomerLinksTransfer409
    | PostV1PhoneLinesIdCustomerLinksTransfer500;
};
