/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';

export type PostV1ProcessingMonthsIdClosePathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Accepted
 */
export type PostV1ProcessingMonthsIdClose202 = any;

/**
 * @description Bad Request
 */
export type PostV1ProcessingMonthsIdClose400 = ApiResponse;

/**
 * @description Not Found
 */
export type PostV1ProcessingMonthsIdClose404 = ApiResponse;

/**
 * @description Conflict
 */
export type PostV1ProcessingMonthsIdClose409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1ProcessingMonthsIdClose500 = ApiResponse;

export type PostV1ProcessingMonthsIdCloseMutationResponse =
  PostV1ProcessingMonthsIdClose202;

export type PostV1ProcessingMonthsIdCloseMutation = {
  Response: PostV1ProcessingMonthsIdClose202;
  PathParams: PostV1ProcessingMonthsIdClosePathParams;
  Errors:
    | PostV1ProcessingMonthsIdClose400
    | PostV1ProcessingMonthsIdClose404
    | PostV1ProcessingMonthsIdClose409
    | PostV1ProcessingMonthsIdClose500;
};
