/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CreatePresignedDownloadUrlInput } from './CreatePresignedDownloadUrlInput.ts';
import type { PresignedUrlModel } from './PresignedUrlModel.ts';

/**
 * @description OK
 */
export type PostV1PreSignedUrlsDownload200 = PresignedUrlModel;

/**
 * @description Bad Request
 */
export type PostV1PreSignedUrlsDownload400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1PreSignedUrlsDownload500 = ApiResponse;

export type PostV1PreSignedUrlsDownloadMutationRequest =
  CreatePresignedDownloadUrlInput;

export type PostV1PreSignedUrlsDownloadMutationResponse =
  PostV1PreSignedUrlsDownload200;

export type PostV1PreSignedUrlsDownloadMutation = {
  Response: PostV1PreSignedUrlsDownload200;
  Request: PostV1PreSignedUrlsDownloadMutationRequest;
  Errors: PostV1PreSignedUrlsDownload400 | PostV1PreSignedUrlsDownload500;
};
