/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CloseProcessingMonthInContingencyInput } from './CloseProcessingMonthInContingencyInput.ts';

export type PostV1ProcessingMonthsIdCloseContingencyPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Accepted
 */
export type PostV1ProcessingMonthsIdCloseContingency202 = any;

/**
 * @description Bad Request
 */
export type PostV1ProcessingMonthsIdCloseContingency400 = ApiResponse;

/**
 * @description Not Found
 */
export type PostV1ProcessingMonthsIdCloseContingency404 = ApiResponse;

/**
 * @description Conflict
 */
export type PostV1ProcessingMonthsIdCloseContingency409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1ProcessingMonthsIdCloseContingency500 = ApiResponse;

export type PostV1ProcessingMonthsIdCloseContingencyMutationRequest =
  CloseProcessingMonthInContingencyInput;

export type PostV1ProcessingMonthsIdCloseContingencyMutationResponse =
  PostV1ProcessingMonthsIdCloseContingency202;

export type PostV1ProcessingMonthsIdCloseContingencyMutation = {
  Response: PostV1ProcessingMonthsIdCloseContingency202;
  Request: PostV1ProcessingMonthsIdCloseContingencyMutationRequest;
  PathParams: PostV1ProcessingMonthsIdCloseContingencyPathParams;
  Errors:
    | PostV1ProcessingMonthsIdCloseContingency400
    | PostV1ProcessingMonthsIdCloseContingency404
    | PostV1ProcessingMonthsIdCloseContingency409
    | PostV1ProcessingMonthsIdCloseContingency500;
};
