/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CreatePresignedUploadUrlInput } from './CreatePresignedUploadUrlInput.ts';
import type { PresignedUrlModel } from './PresignedUrlModel.ts';

/**
 * @description OK
 */
export type PostV1PreSignedUrlsUpload200 = PresignedUrlModel;

/**
 * @description Bad Request
 */
export type PostV1PreSignedUrlsUpload400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1PreSignedUrlsUpload500 = ApiResponse;

export type PostV1PreSignedUrlsUploadMutationRequest =
  CreatePresignedUploadUrlInput;

export type PostV1PreSignedUrlsUploadMutationResponse =
  PostV1PreSignedUrlsUpload200;

export type PostV1PreSignedUrlsUploadMutation = {
  Response: PostV1PreSignedUrlsUpload200;
  Request: PostV1PreSignedUrlsUploadMutationRequest;
  Errors: PostV1PreSignedUrlsUpload400 | PostV1PreSignedUrlsUpload500;
};
