/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CustomerAttachmentResponse } from './CustomerAttachmentResponse.ts';
import type { RegisterCustomerAttachmentInput } from './RegisterCustomerAttachmentInput.ts';

export type PostV1CustomersIdAttachmentsPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Created
 */
export type PostV1CustomersIdAttachments201 = CustomerAttachmentResponse;

/**
 * @description Bad Request
 */
export type PostV1CustomersIdAttachments400 = ApiResponse;

/**
 * @description Not Found
 */
export type PostV1CustomersIdAttachments404 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1CustomersIdAttachments500 = ApiResponse;

export type PostV1CustomersIdAttachmentsMutationRequest =
  RegisterCustomerAttachmentInput;

export type PostV1CustomersIdAttachmentsMutationResponse =
  PostV1CustomersIdAttachments201;

export type PostV1CustomersIdAttachmentsMutation = {
  Response: PostV1CustomersIdAttachments201;
  Request: PostV1CustomersIdAttachmentsMutationRequest;
  PathParams: PostV1CustomersIdAttachmentsPathParams;
  Errors:
    | PostV1CustomersIdAttachments400
    | PostV1CustomersIdAttachments404
    | PostV1CustomersIdAttachments500;
};
