/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CreateCustomerCommand } from './CreateCustomerCommand.ts';
import type { CreateCustomerResponse } from './CreateCustomerResponse.ts';

/**
 * @description Created
 */
export type PostV1Customers201 = CreateCustomerResponse;

/**
 * @description Bad Request
 */
export type PostV1Customers400 = ApiResponse;

/**
 * @description Conflict
 */
export type PostV1Customers409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1Customers500 = ApiResponse;

export type PostV1CustomersMutationRequest = CreateCustomerCommand;

export type PostV1CustomersMutationResponse = PostV1Customers201;

export type PostV1CustomersMutation = {
  Response: PostV1Customers201;
  Request: PostV1CustomersMutationRequest;
  Errors: PostV1Customers400 | PostV1Customers409 | PostV1Customers500;
};
