/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { ProviderInvoiceImportRequestInput } from './ProviderInvoiceImportRequestInput.ts';
import type { RequestProviderInvoiceImportResponse } from './RequestProviderInvoiceImportResponse.ts';

/**
 * @description Created
 */
export type PostV1ProviderInvoices201 = RequestProviderInvoiceImportResponse;

/**
 * @description Bad Request
 */
export type PostV1ProviderInvoices400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1ProviderInvoices500 = ApiResponse;

export type PostV1ProviderInvoicesMutationRequest =
  ProviderInvoiceImportRequestInput;

export type PostV1ProviderInvoicesMutationResponse = PostV1ProviderInvoices201;

export type PostV1ProviderInvoicesMutation = {
  Response: PostV1ProviderInvoices201;
  Request: PostV1ProviderInvoicesMutationRequest;
  Errors: PostV1ProviderInvoices400 | PostV1ProviderInvoices500;
};
