/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { AssignPhoneLineCustomerInput } from './AssignPhoneLineCustomerInput.ts';
import type { PhoneLineCustomerLinkResponse } from './PhoneLineCustomerLinkResponse.ts';

export type PostV1PhoneLinesIdCustomerLinksPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type PostV1PhoneLinesIdCustomerLinks200 = PhoneLineCustomerLinkResponse;

/**
 * @description Bad Request
 */
export type PostV1PhoneLinesIdCustomerLinks400 = ApiResponse;

/**
 * @description Not Found
 */
export type PostV1PhoneLinesIdCustomerLinks404 = ApiResponse;

/**
 * @description Conflict
 */
export type PostV1PhoneLinesIdCustomerLinks409 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1PhoneLinesIdCustomerLinks500 = ApiResponse;

export type PostV1PhoneLinesIdCustomerLinksMutationRequest =
  AssignPhoneLineCustomerInput;

export type PostV1PhoneLinesIdCustomerLinksMutationResponse =
  PostV1PhoneLinesIdCustomerLinks200;

export type PostV1PhoneLinesIdCustomerLinksMutation = {
  Response: PostV1PhoneLinesIdCustomerLinks200;
  Request: PostV1PhoneLinesIdCustomerLinksMutationRequest;
  PathParams: PostV1PhoneLinesIdCustomerLinksPathParams;
  Errors:
    | PostV1PhoneLinesIdCustomerLinks400
    | PostV1PhoneLinesIdCustomerLinks404
    | PostV1PhoneLinesIdCustomerLinks409
    | PostV1PhoneLinesIdCustomerLinks500;
};
