/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts';
import type { CreateProcessingMonthInput } from './CreateProcessingMonthInput.ts';
import type { GetProcessingMonthResponse } from './GetProcessingMonthResponse.ts';

/**
 * @description Created
 */
export type PostV1ProcessingMonths201 = GetProcessingMonthResponse;

/**
 * @description Bad Request
 */
export type PostV1ProcessingMonths400 = ApiResponse;

/**
 * @description Internal Server Error
 */
export type PostV1ProcessingMonths500 = ApiResponse;

export type PostV1ProcessingMonthsMutationRequest = CreateProcessingMonthInput;

export type PostV1ProcessingMonthsMutationResponse = PostV1ProcessingMonths201;

export type PostV1ProcessingMonthsMutation = {
  Response: PostV1ProcessingMonths201;
  Request: PostV1ProcessingMonthsMutationRequest;
  Errors: PostV1ProcessingMonths400 | PostV1ProcessingMonths500;
};
