/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PresignedUrlModel = {
  /**
   * @type string
   */
  url: string;
  /**
   * @type string
   */
  http_method: string;
  /**
   * @type string, date-time
   */
  expires_at_utc: string;
};
