/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProviderInvoiceImportRequestInput = {
  /**
   * @type string
   */
  provider_id: string;
  /**
   * @type string
   */
  processing_month_id: string;
  /**
   * @type string
   */
  storage_bucket: string;
  /**
   * @type string
   */
  storage_object_key: string;
  /**
   * @type null,string
   */
  original_file_name: string | null;
};
