/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RegisterCustomerAttachmentInput = {
  /**
   * @type null,string
   */
  title: string | null;
  /**
   * @type string
   */
  original_file_name: string;
  /**
   * @type string
   */
  storage_bucket: string;
  /**
   * @type string
   */
  storage_object_key: string;
  /**
   * @type null,string
   */
  content_type?: string | null;
  /**
   * @type null,integer, int64
   */
  size_bytes?: number | null;
};
