/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RequestProviderInvoiceImportResponse = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  processing_month_id: string;
  /**
   * @type string
   */
  status: string;
  /**
   * @type null,string
   */
  error: string | null;
  /**
   * @type null,string, date-time
   */
  completed_at: string | null;
};
