/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TransferPhoneLineCustomerInput = {
  /**
   * @type string
   */
  customer_id: string;
  /**
   * @type null,string, date
   */
  transfer_date: string | null;
};
