/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateBillingCycleInput = {
  /**
   * @type string
   */
  provider_id: string;
  /**
   * @type string
   */
  code: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string, date
   */
  start_date: string;
  /**
   * @type string, date
   */
  end_date: string;
};
